// Extra practical sections for the shorter guides, appended to their existing text in lib/posts.js.
// Same block format as lib/guides.js. Keep statements in line with what the tools really do.
export const added = {
'how-to-create-permanent-qr-codes': [
  { h: 'Worked example: a menu code for a small cafe' },
  { ol: [
    'Put the menu online first, as a web page or a PDF with a public link, and open that link on a phone that is not signed in to your accounts. If it asks for a login, customers will be stuck too.',
    'Copy the full address, including https, into the generator and create the code.',
    'Download the image and place it in your table card design. Do not stretch it in one direction only: a QR code has to stay square.',
    'Print one copy and scan it with two or three different phones, from the distance a seated customer would hold it.',
    'Only then print the full batch.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Encoding a link that will change. A static code stores the address itself, so if the page moves, every printed code is dead. Use an address on your own website that you control and can keep stable.',
    'Very long addresses. More text means more and smaller squares, which are harder to scan. Remove tracking parts from the link if you do not need them.',
    'Printing too small or on a glossy, curved surface. Reflections and bends stop cameras from reading the pattern.',
    'Inverting the colours. Light squares on a dark background fail in some scanner apps. Dark on light is the safe choice.',
    'Enlarging the downloaded image a lot for a poster. It will get soft edges. For large formats, ask your print shop what size they need.',
  ] },
  { h: 'When a static code is not the right choice' },
  { p: 'A static code cannot be changed after printing, and it cannot count scans. If you need to change the destination later or want statistics, you need a redirect service, which brings the dependency this guide warns about: the code works only as long as that service does. A middle way is to point the code at a short address on your own domain and change where that address leads whenever you need to.' },
  { h: 'Checklist' },
  { ul: [
    'The link opens without a login on a phone.',
    'The address will stay the same for as long as the print is in use.',
    'The code is dark on light with a clear margin around it.',
    'A printed test copy scans on more than one phone.',
  ] },
],
'how-to-count-words-and-reading-time': [
  { h: 'What the DocBrio counter shows, exactly' },
  { p: 'The tool reports four numbers: words, characters, sentences and minutes of reading time. Words are counted as groups of characters separated by spaces or line breaks. The character count includes spaces and line breaks. Reading time is the word count divided by 200, rounded, with a minimum of one minute. Paragraphs and speaking time are not shown, so for a speech, work it out yourself from the word count using the range mentioned above.' },
  { h: 'Worked example: an essay with a 500 word limit' },
  { ol: [
    'Paste only the body of the essay. Leave out the title, your name and the reference list unless the rules say they count.',
    'Suppose the counter shows 547 words. You need to lose about 50.',
    'Look for sentences that repeat a point, and for long openings such as "It is important to note that". Cutting these costs nothing in meaning.',
    'Paste the shortened text again and check the count. Aim to finish a little under the limit, not exactly on it.',
  ] },
  { h: 'Why your count may differ from another tool' },
  { ul: [
    'Hyphenated words: some programs count "well-known" as one word and others as two. This counter treats anything without a space as one word.',
    'Numbers, dates and web addresses each count as one word here.',
    'Characters with or without spaces: forms that limit characters usually count spaces, but not always. Read the instructions of the form.',
    'Footnotes and text boxes are counted by some word processors only if you tick an option.',
  ] },
  { p: 'When a limit is strict, the count that matters is the one made by whoever set the limit. If a university says the count is taken from Microsoft Word, check the final version there, and leave a small safety margin.' },
  { h: 'When a counter is not enough' },
  { p: 'A word count measures length, not quality or readability. A text can hit the target exactly and still be hard to read. Reading time is also only an average: technical material, or text in a second language, takes readers noticeably longer than the estimate.' },
],
'how-to-convert-text-case-instantly': [
  { h: 'Worked example: cleaning up a pasted product list' },
  { p: 'You copied twenty product names from a supplier sheet and all of them are in capitals, such as COTTON BED SHEET KING SIZE. For your own catalogue you want them in title style.' },
  { ol: [
    'Paste the whole list into the converter. Line breaks are kept, so each product stays on its own line.',
    'Choose Title Case. Every word now starts with a capital letter.',
    'Read through the list for brand names and abbreviations. A brand written as iPhone or a size code such as XL will have become Iphone or Xl and must be fixed by hand.',
    'Copy the result back into your sheet.',
  ] },
  { h: 'What automatic conversion cannot know' },
  { ul: [
    'Names and places in sentence case. The converter capitalises the first letter of each sentence. It cannot tell that karachi or ahmed inside a sentence is a name.',
    'Abbreviations. NASA, PDF and CEO become Nasa, Pdf and Ceo in title case, and all lower case in sentence case.',
    'Small words in headlines. Editorial styles often keep words like of, and, the in lower case inside a title. The tool capitalises every word, so adjust those if your style guide asks for it.',
    'The word I in English, which should stay a capital in sentence case. Check for it after converting.',
  ] },
  { h: 'When not to change case automatically' },
  { p: 'Do not run code, passwords, email addresses with capital letters in systems that are case sensitive, or product codes through a converter. A reference number such as aB12x is a different number in capitals. Languages without capital letters, such as Urdu or Arabic, are simply passed through unchanged, which is harmless but pointless.' },
  { h: 'A quick proofreading routine' },
  { ul: [
    'Convert.',
    'Search the result for the names, brands and abbreviations you know are in the text.',
    'Check the first word after every full stop and colon.',
    'Read the first and last line once, since those are the ones people notice.',
  ] },
],
'how-to-convert-powerpoint-to-pdf': [
  { h: 'What carries over and what does not' },
  { p: 'It is worth being precise here. The DocBrio converter draws the text, pictures, shapes and tables of each slide. It does not draw charts, SmartArt diagrams, animations or transitions, and it replaces fonts it does not have. A deck made mostly of text and photos comes through well. A deck built around charts will have gaps where the charts were.' },
  { h: 'Worked example: lecture slides for a class' },
  { ol: [
    'Save the presentation as .pptx. Older .ppt files have to be saved again in the newer format.',
    'Before converting, look through the deck for charts and SmartArt. For each one, right click it in PowerPoint and save it as a picture, then put that picture on the slide in its place. Pictures are converted reliably.',
    'Convert, then open the PDF and click through every page next to the original deck.',
    'Check slides that used animation to reveal points one by one. In a PDF, everything on the slide shows at once, and overlapping items that were meant to appear in turn may now cover each other.',
    'Share the PDF.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Sending the PDF without paging through it.',
    'Forgetting that speaker notes are not included. If the audience needs them, add the key points to the slides or send a separate document.',
    'Relying on embedded video or audio. A PDF page is a still image of the slide.',
    'Using a rare font for headings. It will be swapped for a standard font and line breaks may shift.',
  ] },
  { h: 'When to export from PowerPoint instead' },
  { p: 'If you have PowerPoint, Google Slides or Keynote open anyway, their own export to PDF reproduces charts, fonts and layouts exactly, and can add notes pages or several slides per sheet. Use that for important decks. The browser converter is for the moments when you have only the file and a browser: on a phone, on a borrowed computer, or when someone sends you a .pptx you just need to read or print.' },
  { h: 'Checklist' },
  { ul: [
    'The file is .pptx.',
    'Charts and SmartArt are replaced by pictures.',
    'Animated slides still make sense as a single still page.',
    'I compared the PDF with the deck, slide by slide.',
  ] },
],
'how-to-turn-pdf-into-powerpoint-slides': [
  { h: 'Know what you get: pictures of pages' },
  { p: 'Each PDF page becomes one slide, and the page is placed on that slide as an image. You cannot click into the old text and retype it. What you can do is put your own text boxes, arrows and highlights on top, and add speaker notes below. The slide takes the shape of the PDF page, so an upright A4 report gives upright slides, which look narrow on a wide projector screen.' },
  { h: 'Worked example: presenting four pages of a long report' },
  { ol: [
    'Do not convert all sixty pages. Note the page numbers you really want to show.',
    'Convert the PDF and open the .pptx file.',
    'Delete every slide except the ones you noted.',
    'On each remaining slide, add one short text box that says what the audience should look at, and a rectangle or arrow that points to the figure or paragraph.',
    'Add a title slide at the start and a summary slide at the end in your own words.',
    'Run the slide show once on the screen you will present on, and check that small print is readable from the back of the room.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Showing full text pages. A page written to be read at a desk is unreadable on a projector. Crop to the chart or table that matters, using the crop function of your presentation program.',
    'Presenting upright pages on a wide screen without adjusting. Either crop to the relevant part or accept wide empty bands at the sides.',
    'Expecting to correct a typo in the page. The page is a picture. Cover the word with a small filled box and type over it if you must.',
    'Converting a very long PDF on a phone. Every page is rendered as an image, which needs memory. Use a computer for large files.',
  ] },
  { h: 'When a different approach is better' },
  { p: 'If you need to rework the wording of the document itself, convert the PDF to Word and build slides from that text. If you only want to show the PDF as it is, most PDF viewers have a full screen or presentation mode, and no conversion is needed. Converting to slides makes sense when you want to add your own commentary around selected pages.' },
  { h: 'Checklist' },
  { ul: [
    'Only the pages I need are in the deck.',
    'Each slide has one clear point marked on it.',
    'The text can be read from a distance.',
    'I have the right to present this material.',
  ] },
],
'how-to-edit-and-whiteout-pdf-pages': [
  { h: 'Important: whiteout hides, it does not delete' },
  { p: 'This point matters enough to state on its own. The Whiteout tool draws a white rectangle over part of the page. The text or picture underneath is still inside the file. Someone who selects and copies text from that area, or who opens the PDF in an editor and moves the rectangle, can get the hidden content back. Whiteout is fine for covering a typing mistake. It is not a safe way to remove an account number, an identity number or any other confidential detail before you share a document.' },
  { p: 'To remove sensitive content for real, use software with a proper redaction function, which deletes the underlying data. A simple alternative that works anywhere: cover the detail, print the page, and scan the printout. The scan contains only what was visible.' },
  { h: 'Worked example: filling in a form that is not interactive' },
  { ol: [
    'Open the form in the Edit PDF tool.',
    'Choose Text and click at the start of the first blank line. Type your answer.',
    'Continue down the page. For tick boxes, type a capital X into the box.',
    'Zoom in and check that your text sits on the lines and does not overlap the printed labels.',
    'Save the PDF and open the saved file once before sending it.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Using whiteout as redaction, as explained above.',
    'Covering a mistake with white on a page whose background is not white. On a cream or grey scan, the patch will show.',
    'Changing documents you are not entitled to change. Altering an invoice, a certificate or a signed contract can be fraud, however easy the tool makes it.',
    'Typing long paragraphs. The tool is made for short additions. For rewriting, convert the PDF to Word.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'The PDF will not load: it may be password protected or locked against editing. Ask the sender for an open copy.',
    'Your typed text looks different from the printed text: the tool uses a standard font and cannot match the original typeface. Keep additions short so the difference does not stand out.',
  ] },
],
'how-to-crop-pdf-pages-and-margins': [
  { h: 'Cropping hides, it does not delete' },
  { p: 'A cropped PDF page is like a photo behind a smaller frame. The page becomes smaller and viewers show only the area you kept, but the content outside that area is still stored in the file, and suitable software can make it visible again. Never crop a page to get rid of confidential information. For that purpose, print the cropped page and scan it, or use proper redaction software.' },
  { h: 'Worked example: an e-ticket for a phone screen' },
  { p: 'A ticket arrives as a full A4 page with the barcode and details in the top third and terms and conditions below. At the gate you want the barcode to fill the screen.' },
  { ol: [
    'Open the PDF in the Crop PDF tool.',
    'Drag a box around the barcode and the passenger details. Leave a small white border around the barcode, because scanners need that quiet space.',
    'Untick the option to crop all pages if the PDF has other pages you want to leave alone.',
    'Crop and download, then open the result and zoom in. The barcode should be sharp, since cropping does not turn the page into a picture.',
    'Keep the original file as well, in case staff ask for the full ticket.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Cropping all pages of a scanned book with one box when the text sits differently on left and right pages. Check several pages before you rely on the result.',
    'Cutting too close. Page numbers, footnotes and the edges of tables are easy to lose.',
    'Cropping for print without checking the paper size. A cropped page is smaller than A4, and a printer may scale it up or centre it with large margins.',
    'Expecting a smaller file. The hidden content is still there, so the file size hardly changes.',
  ] },
  { h: 'When not to crop' },
  { p: 'If you only want to read a document comfortably on a phone, try the zoom or reading mode of your PDF app first, since it changes nothing in the file. If you need one picture out of a page for another document, a screenshot of that area is often quicker. Crop when you want a clean PDF that keeps its sharp, selectable text.' },
  { h: 'Checklist' },
  { ul: [
    'Nothing confidential is being hidden by the crop alone.',
    'The crop box leaves a small margin around the content.',
    'I checked more than one page after cropping all pages.',
    'The original PDF is kept.',
  ] },
],
'how-to-convert-ico-to-png': [
  { h: 'Worked example: recovering a logo from an old website' },
  { p: 'A small business has lost the design files of its logo. The only clean copy anyone can find is the favicon of the website.' },
  { ol: [
    'Open the address of the site followed by /favicon.ico in a browser. If an icon appears, save it. If not, the site may use a PNG or SVG icon instead, which you can find by viewing the page source and searching for the word icon.',
    'Convert the saved .ico file to PNG.',
    'Check the pixel size of the result. If it is 256 pixels, it is usable for documents and small web graphics. If it is 32 or 16, it is only good as a reference.',
    'For anything larger than the pixel size, have the logo redrawn from this reference. A designer can trace a clean version quickly when the shape is simple.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Enlarging a tiny icon and hoping it will sharpen. It will only get blurrier.',
    'Renaming .ico to .png. A few programs cope with that and most do not, because the data inside is still an icon container.',
    'Assuming every site has a favicon.ico. Many modern sites declare their icon in the page and use other formats.',
    'Using the icon of another company in your own material without permission.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'The result has a black background: very old icons store transparency in a way some software ignores. Open the PNG in another viewer before deciding that it is wrong.',
    'The file will not convert: it may be a web page saved under the name favicon.ico, which happens when the site has no icon and returns an error page instead. Open the file in a text editor. If you see HTML, that is the reason.',
    'The colours look reduced: early icons were limited to 16 or 256 colours. That is how the icon was made, and conversion cannot add colours.',
  ] },
  { h: 'When you do not need to convert' },
  { p: 'If you only want to see what an icon looks like, most desktop browsers will display an .ico file when you drag it into a tab. And if the site also offers its logo as SVG or a large PNG, take that file. It will be better than anything inside the favicon.' },
],
'how-to-create-favicon-ico-from-png': [
  { h: 'Worked example: from a wide logo to a working favicon' },
  { p: 'Your logo is a symbol followed by the company name, about four times wider than it is tall. Converted as it is, the icon would be a thin unreadable strip in the middle of an empty square.' },
  { ol: [
    'Open the logo in any image editor and crop it to the symbol alone, as a square.',
    'If the symbol touches the edges, add a little empty space around it, so it does not look cramped in a browser tab.',
    'Export a PNG of 512 by 512 pixels with a transparent background. Anything from 256 pixels up gives the full set of sizes.',
    'Convert it to ICO and rename the download to favicon.ico.',
    'Upload it to the main folder of the site and load the home page in a private window to see the result.',
    'Look at the tab on both a light and a dark browser theme. A dark symbol can vanish on a dark tab bar. A thin light outline or a coloured tile behind the symbol solves that.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Using the full logo with text. At 16 pixels, text is noise.',
    'Starting from a tiny PNG. The tool will not invent the larger sizes, so the icon looks soft on sharp screens and as a desktop shortcut.',
    'Leaving a white background in the PNG. The favicon then appears as a white square, which looks wrong on dark tab bars.',
    'Forgetting the cache. You change the file, see the old icon and assume the upload failed.',
    'Putting the file in a subfolder without telling the page. Browsers look in the main folder by default.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'The icon does not show at all: open the address of your site followed by /favicon.ico. If you get an error page, the file is in the wrong place or has the wrong name.',
    'It shows in one browser but not another: clear the cache of the second browser or wait. Each browser refreshes favicons on its own schedule.',
    'It looks blurry in the tab: the symbol has too much detail for 16 pixels. Simplify the artwork.',
  ] },
  { h: 'Beyond favicon.ico' },
  { p: 'An ICO file covers browser tabs, bookmarks and Windows shortcuts. Phones and tablets use separate PNG icons when someone adds your site to the home screen, and those are declared in the page head or in a web app manifest. If that matters to you, export extra PNG files from the same square artwork. The ICO converter does not create them.' },
],
'how-to-convert-png-to-webp-for-speed': [
  { h: 'Worked example: a blog post with five screenshots' },
  { ol: [
    'Before converting, check the pixel width of the screenshots. If your article column is 800 pixels wide and the screenshots are 2800 pixels wide, resize them first. No format change saves as much as removing pixels nobody will see.',
    'Convert the resized PNG files to WebP at quality 90, since they contain text.',
    'Compare each pair of sizes in the result list. Keep the WebP where it is clearly smaller.',
    'Upload the WebP files and view the published post on a phone. Zoom into the text of one screenshot to confirm that it is still crisp.',
    'Store the PNG files in a folder outside the website as your originals.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Converting without resizing. A huge picture in a better format is still a huge picture.',
    'Using one low quality value for everything. Photos tolerate it. Screenshots with small text do not.',
    'Replacing files on a live site without updating the links. If the page still points to image.png and you deleted it, visitors see a broken image.',
    'Converting logos that would be better as SVG. A logo drawn as vector artwork stays sharp at every size and is often smaller than any pixel format.',
    'Expecting a miracle for page speed. Images are one part of it. Slow hosting, heavy scripts and too many fonts are not fixed by WebP.',
  ] },
  { h: 'How to tell whether it helped' },
  { p: 'Measure before and after. The developer tools of your browser have a Network tab that lists every file a page loads together with its size, so you can add up the image weight with the old files and with the new ones. Free page speed tests from search engines and hosting companies also report image savings. If the total barely moves, your images were not the main problem.' },
  { h: 'When to leave PNG alone' },
  { p: 'Keep PNG for files people will download and reuse, such as press logos and templates, because not everyone can open WebP. Keep it as well for tiny interface icons, where the saving is a few bytes, and wherever your content system does not accept WebP uploads.' },
  { h: 'Checklist' },
  { ul: [
    'The images are resized to the width they are shown at.',
    'Quality is chosen per type of picture.',
    'Every link on the site points to a file that exists.',
    'The originals are stored safely.',
  ] },
],
'how-to-convert-avif-to-png': [
  { h: 'Worked example: an AVIF picture for a school report' },
  { p: 'A student saves a diagram from a science website for a report written in a word processor. The file is named diagram.avif and the Insert Picture dialog does not even list it.' },
  { ol: [
    'Check the licence or the terms of the website, and note the source for the list of references.',
    'Open the AVIF to PNG tool in an up to date browser and choose the file.',
    'Convert and download diagram.png.',
    'Insert the PNG into the report. If the document becomes very heavy because the PNG is large, convert the PNG to JPG for photos. For a diagram with text and lines, keep the PNG, since it stays sharper.',
  ] },
  { h: 'Other ways to get a usable file' },
  { ul: [
    'Try saving again. Some sites serve JPG or PNG when you open the image in a new tab or use a download button, if they offer one.',
    'Take the original from the owner. For a company logo or a press photo, the media page usually provides standard formats.',
    'Update your software. Newer versions of many viewers and editors open AVIF directly, sometimes after installing a free extension from the maker of the system.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Renaming the file to .png or .jpg. The content stays AVIF and most programs will refuse it.',
    'Taking a screenshot of the picture. You capture it at screen size and lose any transparent background.',
    'Mixing up AVIF and HEIC. Photos from an iPhone that end in .heic are a different format and need a different conversion.',
    'Trying on a very old browser and concluding that the file is broken.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'The message says the file could not be opened: update the browser, or try another browser on the same device.',
    'The picture looks pale or flat: it may have been a high dynamic range image. Standard PNG cannot hold that range. An editor that supports it is needed for an exact result.',
    'Only one frame was saved: the AVIF was an animation.',
  ] },
  { h: 'When not to convert' },
  { p: 'If the picture is going onto your own website, AVIF is already an efficient format for that and converting to PNG would make the page heavier. Convert only for editing, documents and programs that cannot read it.' },
],
'how-to-convert-png-to-avif': [
  { h: 'Worked example: one large hero image' },
  { p: 'The biggest saving on most pages comes from the biggest picture, so start with a single test, not with the whole media library.' },
  { ol: [
    'Take the large image at the top of your home page as a PNG, resized to the width at which it is displayed.',
    'Convert it to AVIF at quality 60. Note the time it takes and the new size.',
    'Convert the same PNG to WebP at quality 80 for comparison.',
    'Open the original and both results side by side at full size. Look at smooth areas such as sky and at fine detail such as hair or text.',
    'Choose the smallest file that you cannot tell apart from the original at normal viewing distance.',
    'Publish it with a fallback, as described below, and keep the PNG.',
  ] },
  { h: 'Serving AVIF safely' },
  { p: 'HTML has a picture element made for this situation. You list the AVIF file first, a WebP or PNG second, and a normal image tag last. Each browser takes the first format it understands, so older browsers quietly get the fallback and nobody sees a broken image. Many content systems and image plugins write this markup for you. If yours accepts only one file per image, WebP is the more practical single choice.' },
  { h: 'Common mistakes' },
  { ul: [
    'Converting hundreds of images in a browser tab. AVIF encoding is slow. For bulk work, a build tool or an image service is the right approach. This converter suits a handful of important pictures.',
    'Publishing AVIF without a fallback.',
    'Pushing the quality very low. AVIF hides its loss well in a small preview, but fine textures turn smooth and waxy. Check at full size.',
    'Using AVIF for images people will download, such as a logo pack or a wallpaper.',
    'Judging by file size alone, without looking at the picture.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'Conversion fails on a large image: resize it first. Encoding needs far more memory than the size of the file suggests.',
    'The upload is rejected by your site: the system may not allow the AVIF file type. Check its settings or documentation.',
    'The image does not appear for some visitors: they are using an older browser and no fallback was provided.',
  ] },
  { h: 'When AVIF is not worth it' },
  { p: 'For small pictures, the difference between AVIF and WebP is a few kilobytes and not worth the extra handling. For a site with few visitors and few images, time is better spent on resizing pictures correctly. AVIF pays off on image heavy pages that receive real traffic.' },
],
'how-to-convert-jpg-to-png': [
  { h: 'Worked example: preparing a product photo for a cut out' },
  { ol: [
    'Start from the best JPG you have, ideally straight from the camera or phone, not a copy that came through a chat app.',
    'Convert it to PNG once.',
    'Open the PNG in your image editor and remove the background. Save your working file in the format of the editor if it has one, so the layers are kept.',
    'Export the finished cut out as PNG, which keeps the transparent area.',
    'For places that do not need transparency, such as a marketplace listing with a white background, also export a JPG copy. It will be far smaller.',
  ] },
  { p: 'The conversion in step two did not improve the photo. It moved it into a format that will not get worse during steps three and four, and that can store the transparency you are about to create.' },
  { h: 'Common mistakes' },
  { ul: [
    'Converting to PNG and uploading the result to a website. The page gets heavier and the picture looks the same.',
    'Expecting the blocky marks of a heavily compressed JPG to go away. They are part of the picture now.',
    'Converting, editing and then saving as JPG after every small change. The loss returns with each save. Save as JPG once, at the end.',
    'Filling a phone with PNG copies of photos. They can take several times the space of the JPG files.',
  ] },
  { h: 'How to see that nothing was gained' },
  { p: 'Open the JPG and the PNG side by side and zoom in until you can see single pixels. They are identical. The only differences are the size of the file and what will happen the next time you save it. That simple test is worth doing once, because it settles the question of whether conversion improves quality for good.' },
  { h: 'When you do not need this conversion' },
  { ul: [
    'Your editor opens JPG and saves its own project format. Then work in that format and skip the PNG step.',
    'You are making one small edit, such as a crop. One extra JPG save at high quality does no visible harm.',
    'The destination accepts JPG. Check the list of allowed formats before converting. Many forms that mention PNG accept JPG too.',
  ] },
  { h: 'Checklist' },
  { ul: [
    'I have a real reason for PNG: a requirement, repeated editing, or transparency to come.',
    'I am starting from the best copy of the JPG.',
    'I have room for a file that is several times larger.',
    'I will export a JPG again for sharing when the work is finished.',
  ] },
],
'how-to-convert-png-to-jpg': [
  { h: 'Worked example: emailing six screenshots to support' },
  { p: 'You are reporting a problem to a software company and have six full screen captures. Together they exceed the attachment limit of the support form.' },
  { ol: [
    'Before converting, crop each screenshot to the window or message that matters. This removes most of the pixels and protects your privacy, since the rest of your desktop is no longer visible.',
    'Select all six PNG files in the converter and set the quality to 90, because the error messages must stay readable.',
    'Convert and download everything as one ZIP file, or attach the six JPG files separately if the form does not take ZIP files.',
    'Open one of the JPG files and read the smallest text in it before you send.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Sending uncropped screenshots. Besides the size, they often show browser tabs, notifications and file names you did not mean to share.',
    'Choosing a low quality for screenshots of text. Support staff cannot help if they cannot read the error code.',
    'Converting logos and diagrams. Flat graphics often stay smaller and cleaner as PNG.',
    'Deleting the PNG files straight away. If someone asks for a clearer copy, you will want them.',
    'Converting a picture with a transparent background and being surprised by the white fill.',
  ] },
  { h: 'Choosing between JPG and a smaller PNG' },
  { p: 'JPG is not the only way to shrink a screenshot. If the capture is mostly flat interface with little photographic content, cropping and reducing its width may bring the PNG under the limit while keeping the text perfect. A simple test: convert once and compare. If the JPG is not at least half the size of the PNG, the picture is probably better left as PNG and made smaller in pixels instead.' },
  { h: 'Troubleshooting' },
  { ul: [
    'The form still says the file is too large: check whether the limit applies to each file or to all attachments together.',
    'Colours look slightly washed out: screenshots from wide colour displays can shift a little in conversion. For support and forms this does not matter. For design work, keep the PNG.',
    'A ZIP file is refused: attach the JPG files one by one.',
  ] },
  { h: 'Checklist' },
  { ul: [
    'Each screenshot is cropped to what matters.',
    'Nothing private is visible.',
    'The text is readable in the JPG.',
    'The total size is under the limit.',
  ] },
],
'how-to-convert-jpg-to-ico-favicon': [
  { h: 'Worked example: a folder icon from a holiday photo' },
  { ol: [
    'Pick a photo with one clear subject. A single face or a landmark against the sky works. A group on a beach does not.',
    'Crop it to a square, tight around the subject. In a tiny icon, background is wasted space.',
    'If the photo is dark, brighten it a little. Small icons on a busy desktop need contrast.',
    'Convert the square JPG to ICO.',
    'In Windows, right click the folder, open Properties, go to the Customize tab and choose Change Icon. Browse to your .ico file and confirm.',
    'Keep the .ico file in a place where it will stay, such as a dedicated Icons folder. If you move or delete it, the folder falls back to the standard icon.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Skipping the square crop. The picture is then fitted with empty bands and looks smaller than the other icons.',
    'Saving the .ico file to the Downloads folder and clearing that folder later.',
    'Using a logo JPG with a white background for a website favicon. It shows as a white square in dark browser themes. A PNG with transparency is the right source for a favicon.',
    'Starting from a small picture taken from a chat app. Chat apps reduce photos, and the larger icon sizes will look soft.',
    'Expecting to recognise fine detail. Test by looking at the icon in the smallest view of your file manager.',
  ] },
  { h: 'Troubleshooting' },
  { ul: [
    'Windows still shows the old icon: icon images are cached. Restarting the computer, or signing out and in again, usually refreshes them.',
    'The icon looks fine when large but muddy when small: there is too much detail. Crop tighter, or choose a simpler picture.',
    'Empty bands appear beside the picture: the JPG was not square. Crop it and convert again.',
  ] },
  { h: 'When to choose a different route' },
  { p: 'For the favicon of a business website, it is worth getting the logo as a PNG or SVG from whoever designed it. A JPG logo carries a solid background and faint compression marks around its edges, and both show up in an icon. For personal shortcuts and folders, a JPG photo is perfectly fine.' },
],
'how-to-convert-ico-to-jpg': [
  { h: 'Worked example: an app icon in a user manual' },
  { p: 'You are writing a short manual in a word processor and want to show the icon that staff should double click. You have the .ico file from the installation folder.' },
  { ol: [
    'Convert the icon to JPG at quality 90 or higher.',
    'Insert the picture into the manual and leave it at its inserted size. If the icon inside the file was 256 pixels, there is room to shrink it. If it was 48 pixels, do not enlarge it.',
    'Place it in line with the text or in a table cell next to the instruction, so it does not float away when the text is edited.',
    'Export the manual to PDF and check how the icon looks on the page.',
  ] },
  { h: 'Icon or screenshot?' },
  { p: 'For manuals there is often a better option than the icon file: a screenshot of the icon as it appears on the desktop, with its label underneath. Readers recognise that immediately, and the size on screen is exactly the size they will see. Use the icon file when you need the clean artwork on its own, for example in a table of applications.' },
  { h: 'Common mistakes' },
  { ul: [
    'Enlarging a small icon to make it noticeable. Put a frame or an arrow next to it instead.',
    'Using the JPG on a coloured page or a dark slide, where its white background becomes a visible box.',
    'Lowering the quality to save space. An icon JPG is only a few kilobytes anyway.',
    'Using the icons of other companies in commercial material without checking their brand rules. Many publish guidelines on how their icon may be shown.',
  ] },
  { h: 'Email signatures in particular' },
  { ul: [
    'Keep the picture small in pixels and in file size. Some mail systems block or strip large images.',
    'Remember that many email programs hide images until the reader allows them. The signature must make sense without the picture.',
    'Dark mode in email apps can put your white backed icon on a dark surface. If that bothers you, use a PNG with transparency.',
  ] },
  { h: 'When to pick PNG instead' },
  { p: 'Choose ICO to PNG whenever the place you are putting the icon accepts PNG, which today is nearly everywhere. PNG keeps the transparent surround and the crisp edges. JPG is the fallback for the few systems, mostly older forms and some mail tools, that refuse anything else.' },
],
'how-to-convert-jpg-to-webp': [
  { h: 'Worked example: a gallery page with twelve photos' },
  { ol: [
    'Export the twelve photos from your editor at the width the gallery displays them, plus a larger version only if visitors can click to enlarge.',
    'Convert the first photo to WebP at 85, 75 and 65. Compare the three results with the JPG at full size.',
    'Pick the lowest setting at which you cannot see a difference in skin, sky and fine patterns. For many photos that is around 75 to 80, but let your own eyes decide.',
    'Convert the other eleven at that setting and check the sizes in the list.',
    'Upload them, open the gallery on a phone using mobile data and see whether it feels faster.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Starting from small, already compressed JPG files. The gain is tiny and the second compression can be seen.',
    'Using one setting without ever looking at a result.',
    'Converting pictures for marketplaces and social networks. Those platforms compress every upload again in their own way, and some do not accept WebP at all.',
    'Forgetting that EXIF data is dropped. If you rely on copyright or caption fields stored in the photo, they will not be in the WebP.',
    'Removing the JPG files from your computer once the site looks fine.',
  ] },
  { h: 'A fair expectation' },
  { p: 'Published comparisons generally find WebP somewhat smaller than JPG at the same visual quality, but how much depends heavily on the photo and on how the JPG was made. For your own pictures, the only number that counts is the one in the result list. If the saving across a page is a few percent, it is not worth the trouble. If your JPG files came straight from a camera at high quality, the saving is usually clear.' },
  { h: 'Troubleshooting' },
  { ul: [
    'The WebP is larger than the JPG: the JPG was strongly compressed already. Keep the JPG.',
    'Skies show bands of colour: raise the quality by ten points for that photo.',
    'The site refuses the upload: your content system may need a setting or an update to allow WebP.',
  ] },
  { h: 'Checklist' },
  { ul: [
    'The photos are for a website.',
    'They are resized to their display width before conversion.',
    'I compared at least one result with its original at full size.',
    'I kept the WebP only where it is clearly smaller.',
    'The JPG originals are stored safely.',
  ] },
],
'how-to-verify-email-addresses-online': [
  { h: 'What the result does and does not tell you' },
  { p: 'It helps to be exact about the limits. The checker confirms that an address is written in a valid form, that its domain exists and that the domain has mail servers. It does not, and cannot, confirm that one particular mailbox exists. An address such as a misspelled name at a large mail provider passes every check and still bounces. The score shown with the result is an estimate based on these checks. It is not a measurement of deliverability.' },
  { h: 'What leaves your browser' },
  { p: 'To look up the mail servers, your browser sends the domain part of the address, meaning everything after the @ sign, to a public DNS service run by Google, or to one run by Cloudflare if the first does not answer. Those services see the domain name and your IP address, as they do for any DNS lookup. The part before the @ sign is not sent, and DocBrio does not receive or store the address. The format check, the disposable domain list and the name suggestion run inside your browser.' },
  { h: 'Worked example: checking a sign up before replying' },
  { ol: [
    'A customer enquiry arrives through your website form with the address sara.khan@gmial.com.',
    'The checker reports either that the domain has no mail servers or that it belongs to an unrelated party. Look at the domain: gmial is a common typing slip for gmail.',
    'Do not correct it silently and send personal details to your guess. If the form also collected a phone number, confirm the address that way.',
    'For your form itself, add a second field that asks people to repeat their address, or send a confirmation link. That prevents the problem at the source.',
  ] },
  { h: 'Common mistakes' },
  { ul: [
    'Treating a pass as proof that a person will receive your message.',
    'Checking a purchased list and then mailing it. A valid format does not give you permission to email someone. Many countries have laws on unsolicited email, and mail providers punish senders who ignore them.',
    'Relying on the suggested name. It is derived from the letters before the @ sign and will be wrong for many addresses.',
    'Rejecting every role address such as info or sales. For a business enquiry, those are often the right contact.',
  ] },
  { h: 'When you need something else' },
  { p: 'To know that an address really works, there is one reliable method: send a confirmation message with a link and wait for the click. For large mailing lists, use the confirmed sign up process of your email service. This checker is suited to single addresses, such as catching a typing error before you send an important message.' },
],
};
