// Long guides. Each one covers what the tool page does not: a worked example, common mistakes, troubleshooting,
// when not to use the method and a checklist. Numbers in the worked examples are illustrations, not measurements.
// Blocks: { p } paragraph, { h } heading, { ol } numbered list, { ul } bullet list.
const UPDATED = '2026-10-10';

export const guides = [
{
  slug: 'how-to-convert-pdf-to-word-for-free',
  title: 'How to Convert PDF to Word for Free Without Extra Software',
  desc: 'What a PDF to Word conversion can and cannot recover, a worked example with a two page CV, and how to fix the usual problems afterwards.',
  date: '2026-10-01', updated: UPDATED, tool: 'pdf-to-word',
  content: [
    { p: 'A PDF is built to look the same everywhere, not to be edited. Inside the file there are no paragraphs, only pieces of text pinned to exact positions on a page. Turning that back into a Word document means guessing which pieces belong together. Once you know that, the results of any converter make much more sense, and you can plan for the clean up.' },
    { h: 'First check: is your PDF text or a picture?' },
    { p: 'Open the PDF and try to select a sentence with your mouse or finger. If single words highlight, the file contains real text and conversion will be quick and accurate. If the whole page highlights as one block, or nothing can be selected, the page is a scan or a photo. A scan has to be read by OCR, which looks at the shapes of the letters. OCR is slower and makes mistakes, mostly with small print, faint copies and handwriting.' },
    { p: 'The OCR in DocBrio recognises English. Pages in Urdu, Arabic or other scripts will not come out correctly when they are scans. If such a PDF contains real text, the text is extracted, but the order of right to left lines may need fixing by hand.' },
    { h: 'Worked example: updating an old CV' },
    { p: 'Imagine a two page CV that exists only as a PDF. The Word file it was made from is long gone, and you need to add a new job.' },
    { ol: [
      'Select some text in the PDF to confirm that it is not a scan.',
      'Open the PDF to Word tool, choose the file and press Convert to Word.',
      'Open the downloaded .docx file in Word or Google Docs. The wording is all there, but as plain paragraphs. A sidebar with contact details now sits above or below the main text instead of beside it.',
      'Apply your heading style to the section titles, turn the lists of duties back into bullet points, and rebuild the sidebar with a two column table if you want it back.',
      'Add the new job, read the whole CV once against the old PDF, and save it. Keep this Word file, so next time you do not need to convert at all.',
    ] },
    { p: 'For two pages this takes ten to fifteen minutes. That is far less than retyping, and you also avoid the typing errors that come with it.' },
    { h: 'Common mistakes' },
    { ul: [
      'Expecting an exact copy. The tool recovers the text. Columns, images, text boxes and decorative fonts are not rebuilt.',
      'Converting a scan and sending the result without reading it. OCR confuses similar shapes, such as the letter l and the digit 1, or the letters rn and m. Always proofread names, dates and amounts.',
      'Editing a signed or official document. Converting a certificate or a signed contract in order to change it can be forgery. Ask whoever issued it for a corrected copy.',
      'Deleting the PDF. Keep it as the reference for how the document is supposed to look.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'Text from two columns is mixed together: the lines were read straight across the page. Cut the text of the second column and paste it after the first.',
      'A table became loose lines of text: for anything with rows and columns, use the PDF to Excel tool, then copy the table from Excel into Word.',
      'The result is empty or nonsense: the file is probably a low quality scan. Scan it again, straighter and at a higher resolution, and retry.',
      'The file will not open in the tool: it may be password protected. Open it with the password and save or print an unprotected copy first.',
    ] },
    { h: 'When another method is better' },
    { p: 'If you only need to add a date, tick a box or cover a small error, do not convert. Use the Edit PDF tool and leave the layout untouched. If the layout must survive exactly, ask the sender for the original Word file, which is always the best source. And if you have Microsoft Word on a computer, try opening the PDF directly in it: Word tries to rebuild the layout, with mixed results on complex pages. Google Docs can open a PDF too, but that means uploading it to your Google account.' },
    { h: 'Checklist' },
    { ul: [
      'I checked whether the PDF contains text or scanned pictures.',
      'I am allowed to edit this document.',
      'I proofread names, dates and numbers after converting.',
      'I restored headings, lists and tables where they matter.',
      'I kept both the original PDF and the new Word file.',
    ] },
  ],
},
{
  slug: 'how-to-convert-pdf-to-excel-spreadsheets',
  title: 'How to Extract Tables from PDF to Excel Spreadsheets',
  desc: 'How table extraction from a PDF works, a worked example with a bank statement, and how to check and clean the numbers before you rely on them.',
  date: '2026-10-02', updated: UPDATED, tool: 'pdf-to-excel',
  content: [
    { p: 'A table in a PDF only looks like a table. The file stores each number and word as a separate piece of text at a position on the page. It has no rows, no columns and no cells. An extraction tool rebuilds the grid from those positions: pieces at the same height become a row, and a wide horizontal gap marks the start of a new column. This works well for tidy tables and less well for crowded ones, so the real job is knowing how to check and repair the result.' },
    { h: 'Worked example: a three page bank statement' },
    { p: 'Say you have a statement with the columns Date, Description, Debit, Credit and Balance, and you want to add up your spending by month.' },
    { ol: [
      'Convert the PDF with the PDF to Excel tool and open the .xlsx file. Each page of the statement is on its own sheet.',
      'Copy the rows from the second and third sheet underneath the rows of the first, so everything is in one list. Delete the header row that repeats on each page.',
      'Look at the Description column. Long descriptions that wrapped onto a second line in the PDF now sit in a row of their own with no date and no amount. Move that text up into the row it belongs to and delete the leftover row.',
      'Click a cell in the Debit column. If the number is aligned to the left, Excel is treating it as text, often because of a thousands separator or a currency sign. Select the column and use Find and Replace to remove the separator or the sign, then set the cell format to Number.',
      'Now the important part: add up the Debit column and compare your total with the total printed on the statement. Do the same for Credit. If both match, the extraction is complete. If not, a row was split or lost, and you can find it by comparing page by page.',
    ] },
    { p: 'That last comparison takes a minute and is the only way to know the data is right. Never skip it for anything involving money.' },
    { h: 'Common mistakes' },
    { ul: [
      'Trusting the numbers without a control total.',
      'Forgetting that debits and credits may land in the same column when the PDF places them close together. Check a few rows against the original.',
      'Leaving numbers as text. Sums over text cells show zero, which looks like a broken formula.',
      'Overlooking dates. A date like 03/04/2026 can be read as the third of April or the fourth of March, depending on the regional settings of Excel. Check one date you know.',
      'Converting a scanned statement and expecting perfect digits. OCR can misread a 5 as a 6. With scans, check every amount.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'Everything is in one column: the gaps between the columns of the PDF are narrow. Use Text to Columns on the Data tab in Excel and split by spaces, then repair the description column.',
      'One column is split into two: a wide gap inside a cell was taken for a column border. Join the two parts with a formula such as =A2&" "&B2, or simply retype the few cells affected.',
      'Rows are out of order: this is rare, and happens with rotated pages. Rotate the page in a PDF viewer, save and convert again.',
    ] },
    { h: 'When not to use this method' },
    { p: 'Look for a better source first. Many banks and accounting systems let you download the same data as a CSV or Excel file, and that will always be cleaner than anything pulled out of a PDF. For a table of five or six rows, typing it is faster than converting and checking. And for tables with merged cells, several lines of text per cell or nested headings, expect to spend real time on repairs.' },
    { h: 'Checklist' },
    { ul: [
      'I looked for a CSV or Excel download before converting.',
      'All pages are combined into one sheet and repeated headers are removed.',
      'Wrapped descriptions are merged back into their rows.',
      'Number columns are real numbers, not text.',
      'My totals match the totals printed in the PDF.',
    ] },
  ],
},
{
  slug: 'how-to-convert-word-to-pdf-cleanly',
  title: 'How to Convert Word Documents to PDF Without Surprises',
  desc: 'Why a Word document can look different after conversion, how to prepare it, a worked example with a cover letter, and when to use Word itself instead.',
  date: '2026-10-02', updated: UPDATED, tool: 'word-to-pdf',
  content: [
    { p: 'Sending a Word file is a small gamble. It can look different on the other computer if a font is missing or the version of Word is older. A PDF removes the gamble, which is why employers, universities and offices usually ask for one. The conversion is simple, but a few details decide whether the PDF looks the way you intended.' },
    { h: 'What happens during the conversion' },
    { p: 'There are two kinds of converter. Word itself, and other full office programs, print the document into a PDF using their own layout engine, so the PDF matches what you saw on screen. A browser tool like the one on DocBrio works differently. It reads the content of the .docx file, meaning the headings, paragraphs, lists, tables and pictures, and lays that content out again on A4 pages. The content arrives complete, but the fine details of the layout are rebuilt and not copied. Line breaks and page breaks can therefore fall in different places.' },
    { h: 'Worked example: a one page cover letter' },
    { ol: [
      'Finish the letter in your editor and save it as .docx. The older .doc format has to be saved again as .docx first.',
      'Keep the structure simple: normal paragraphs, one or two heading levels and ordinary bullet lists. Avoid text boxes and floating shapes, because their position is the first thing to be lost.',
      'Convert the file and open the PDF. Check that the letter still fits on one page. If the last two lines moved to a second page, shorten a sentence or reduce the spacing in the original, and convert again.',
      'Read the PDF from top to bottom once. Look at special characters, bullet symbols and the alignment of the date and the address.',
      'Give the file a clear name, such as Cover-Letter-Your-Name.pdf, before you send it.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'Counting on a decorative font. If the font is not available where the PDF is made, a standard one is used and the look changes. Common fonts are the safe choice for applications.',
      'Relying on headers, footers and automatic page numbers. Browser based converters generally read only the main body of the document, so these parts may be missing. If your name must appear on every page, check the PDF.',
      'Using tabs and spaces to line things up. This breaks as soon as the font or page width changes. Use a table without borders instead.',
      'Sending without opening the PDF. Thirty seconds of checking saves an embarrassing second email.',
      'Leaving tracked changes and comments in the document. Accept or reject all changes before converting, whichever tool you use.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'A table is cut off at the right edge: it is wider than an A4 page. Make the columns narrower or remove one.',
      'Pictures have moved: floating pictures are placed in the text flow. Set them to In Line with Text in the original.',
      'The file will not convert: check that it really is a .docx file and is not open and locked in another program.',
    ] },
    { h: 'When to use Word itself instead' },
    { p: 'If you have Microsoft Word on your computer, use File, then Save As, and choose PDF. That keeps your exact layout, fonts, headers and page numbers, and it is the right choice for a thesis, a designed CV or any long report. Google Docs and LibreOffice have a similar download or export option. A browser converter is the practical choice when you are on a phone, a shared computer or a device without an office program, and the document is fairly plain.' },
    { h: 'Checklist' },
    { ul: [
      'The file is saved as .docx.',
      'Tracked changes are accepted and comments are removed.',
      'The layout uses simple paragraphs, lists and tables.',
      'I opened the PDF and checked the page count and the last line of each page.',
      'The file name tells the receiver what it is and whose it is.',
    ] },
  ],
},
{
  slug: 'how-to-merge-pdf-files-without-software',
  title: 'How to Merge PDF Files into One Document Without Installing Software',
  desc: 'How to combine several PDFs in the right order, with a worked example for a job application, the usual mistakes and what merging cannot do.',
  date: '2026-10-03', updated: UPDATED, tool: 'merge-pdf',
  content: [
    { p: 'Many forms have a single upload button and a short instruction: attach all documents as one PDF. Merging is how you get from a folder of separate files to that one document. It is not difficult, but the order of the pages and the size of the final file are easy to get wrong.' },
    { h: 'Before you start: get the order right' },
    { p: 'A merge tool joins whole files one after another. The simplest way to control the order is to rename the files so they sort the way you want, for example 01-cover-letter.pdf, 02-cv.pdf, 03-degree.pdf. Then select them all together. After you choose the files, the DocBrio tool lists them in the box, and that list is the order they will be joined in. Read it before you press the button.' },
    { h: 'Worked example: a job application' },
    { p: 'You have a cover letter and a CV exported from Word, plus phone scans of your degree and your identity card. The portal accepts one PDF of at most 5 MB.' },
    { ol: [
      'Make sure every document is a PDF. A photo of your degree has to be turned into a PDF first. Most phone scanner apps can save as PDF, and so can the print dialog of most devices.',
      'Rename the four files with numbers at the front, in the order a reader expects: letter, CV, degree, identity card.',
      'Open the Merge PDF tool, select all four files and check the list.',
      'Press Merge PDFs, download the result and open it. Scroll through every page from start to finish.',
      'Check the file size. If it is over 5 MB, the scans are the cause, not the letter or the CV. Scan those pages again at a lower resolution or in greyscale, and merge again.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'Not opening the merged file. Sideways pages, a missing page or the wrong order are only visible when you look.',
      'Expecting the merge to shrink the file. Merging keeps every page exactly as it was, so the result is about as large as all the parts together.',
      'Mixing page sizes without noticing. An A4 letter next to a phone photo in a different shape gives a document whose pages jump in size. It is still valid, but if it will be printed, rescan the odd pages.',
      'Merging the wrong version. If you have CV-final.pdf and CV-final-2.pdf in the same folder, check twice which one you selected.',
      'Putting confidential pages into a shared file. Once merged, the pages travel together. Only include what the receiver asked for.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'A file is reported as damaged or password protected: open it with its password in a PDF viewer and save or print an unprotected copy, then merge that copy.',
      'The browser slows down or the tab closes: very large scans need a lot of memory, especially on a phone. Merge in two halves, or use a computer.',
      'The order is wrong: rename the files with leading numbers and select them again.',
    ] },
    { h: 'What merging does not do' },
    { p: 'Merging puts whole files end to end. It does not reorder single pages inside a file, remove a page or reduce the file size. If you need page 3 of one document between pages 1 and 2 of another, you have to split the files first with a tool that can do that. And if the receiver wants separate files, do not merge at all. Follow their instruction.' },
    { h: 'Checklist' },
    { ul: [
      'Every part is a PDF.',
      'The files are numbered in the order I want.',
      'I read the list of files before merging.',
      'I opened the result and looked at every page.',
      'The file size is under the limit of the form.',
    ] },
  ],
},
{
  slug: 'reduce-image-size-without-losing-quality',
  title: 'How to Reduce Image Size Without Visible Quality Loss',
  desc: 'A practical method for getting a photo under an upload limit: crop, resize, then compress. With a worked example, mistakes to avoid and a checklist.',
  date: '2026-10-03', updated: UPDATED, tool: 'image-compressor',
  content: [
    { p: 'Strictly speaking, you cannot make a photo file much smaller without losing something. What you can do is lose only the things nobody will see. The size of an image file comes from two sources: how many pixels the picture has, and how carefully each area of it is stored. Reducing a file well means dealing with both, in the right order.' },
    { h: 'The order that works: crop, resize, compress' },
    { ol: [
      'Crop. Cut away everything that is not needed. Empty wall around a face is pure wasted file size.',
      'Resize. Bring the width and height down to what the destination needs. A photo for a form does not need the thousands of pixels a phone camera records.',
      'Compress. Save as JPG at a moderate quality and look at the result.',
    ] },
    { p: 'People often jump straight to step three and push the quality lower and lower. That gives an ugly picture that is still too big. Resizing first does most of the work, and it does that work without hurting how the picture looks at its final size.' },
    { h: 'Worked example: a photo for an application form' },
    { p: 'The form asks for a passport style photo as a JPG of at most 100 KB. Your phone photo is several megabytes. The numbers below are an illustration, and yours will differ.' },
    { ol: [
      'Open the photo in the gallery editor of your phone and crop it to head and shoulders.',
      'Resize the cropped picture so that it is roughly 600 to 800 pixels wide. Many gallery apps have a resize option. On Windows, the Photos app and Paint both do.',
      'Open the resized picture in the Image Compressor and compress at quality 70.',
      'Read the After size. If it shows something like 85 KB, you are done. If it is 130 KB, try 60. If you would have to go below about 50, go back and make the picture a little smaller instead.',
      'Look at the eyes and the hair in the preview. Those areas show damage first.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'Compressing a file that was already compressed. Each round of JPG saving adds new marks. Always start again from the original photo.',
      'Using one setting for everything. A face photo survives quality 60. A scan of a certificate with small print may need 85.',
      'Sending photos through a chat app as normal pictures and then reusing them. Most chat apps reduce photos automatically, so the copy you receive back is already degraded. Send as a document or file when quality matters.',
      'Ignoring the minimum. Some forms reject photos that are too small as well. Read the stated range.',
      'Overwriting the original. Keep it. You may need a larger version later.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'The file barely changes size: it may already be a well compressed JPG. Only resizing will help now.',
      'The compressed file is larger than the original: your quality setting is higher than the one the original was saved with. Lower it.',
      'Text in a scanned page looks dirty: raise the quality and reduce the pixel size instead. Or scan in greyscale, which stores less colour information.',
      'Colours look banded in a sky or on a plain wall: that is a sign of too little quality. Go up ten points.',
    ] },
    { h: 'When you should not compress' },
    { p: 'Do not compress the only copy of a photo you care about. Do not compress pictures you plan to print large. Be careful with documents where every character matters, such as an identity card or a bank form, since an unreadable digit can get an application rejected. And for logos or drawings with flat colours, JPG compression is the wrong tool. Those stay cleaner and often smaller as PNG or WebP.' },
    { h: 'Checklist' },
    { ul: [
      'I know the size limit, the allowed format and any minimum size.',
      'I cropped and resized before compressing.',
      'I started from the original, not from a forwarded copy.',
      'I checked faces and text in the preview.',
      'The original file is still saved somewhere.',
    ] },
  ],
},
{
  slug: 'how-to-convert-webp-to-png',
  title: 'How to Convert WebP Images into PNG Files That Open Everywhere',
  desc: 'Why pictures saved from websites end in .webp, a worked example with a logo for a presentation, and how to avoid needing a conversion at all.',
  date: '2026-10-06', updated: UPDATED, tool: 'webp-to-png',
  content: [
    { p: 'You save a picture from a website and plan to drop it into a presentation. The file ends in .webp, and the program refuses it. Nothing is wrong with the file or with your computer. The picture is simply in a format that was made for browsers and that some other software has not caught up with.' },
    { h: 'Three ways to deal with a WebP file' },
    { ul: [
      'Convert it. This always works, and it is what the rest of this guide describes.',
      'Open it with a program that already understands WebP. Recent versions of Windows and macOS come with viewers that can open WebP, and some of them can save a copy in another format. If yours can, that is just as good.',
      'Look for the original. Some sites offer a download button that gives you the JPG or PNG the owner uploaded. For a company logo, the press or media page of the company often has proper files.',
    ] },
    { h: 'Worked example: a logo for a slide' },
    { p: 'You need the logo of a partner organisation on a title slide with a dark blue background. You saved the logo from their website and it arrived as logo.webp.' },
    { ol: [
      'Open the WebP to PNG tool and choose logo.webp.',
      'Press Convert to PNG and look at the preview. If the area around the logo shows the page behind it, the background is transparent, which is what you want on a coloured slide.',
      'Download logo.png and insert it into the slide.',
      'Zoom the slide to full screen. If the logo looks soft, the picture from the website was small. Ask the organisation for a larger file. Do not stretch this one.',
    ] },
    { p: 'PNG was the right target here for two reasons. It kept the transparent background, so no white box appears on the dark slide. And it stores flat colours and sharp edges exactly, which is what a logo consists of. For a photograph going into an email, JPG would have been the better choice because the file would be much smaller.' },
    { h: 'Common mistakes' },
    { ul: [
      'Renaming the file. Changing .webp to .png in the file name does not convert anything. Some programs detect the real format and cope, and others show an error.',
      'Converting everything to PNG out of habit. A PNG of a large photo can be many megabytes. Use PNG for graphics and for transparency, and JPG for photos.',
      'Taking a screenshot instead. A screenshot captures the picture at the size it has on your screen, together with whatever is behind it, and loses the transparency.',
      'Using pictures you have no right to use. Being able to save an image from a website does not make it free to use. Check the licence, or ask the owner.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'The background came out black or white, not transparent: the WebP never had a transparent background. The website put it on a matching colour. An image editor is needed to cut it out.',
      'Only one frame was saved: the WebP was an animation. A PNG can hold only a still picture.',
      'The file will not open in the tool either: the download may be incomplete. Save the picture again from the website.',
    ] },
    { h: 'When converting is not the answer' },
    { p: 'If the picture is going back onto a website, leave it as WebP, since it is already in the best format for that. If you need a large, sharp version for print, converting will not help, because the web copy is small. You need the original artwork from its owner.' },
    { h: 'Checklist' },
    { ul: [
      'I am allowed to use this image.',
      'I chose PNG because I need transparency or sharp edges. Otherwise JPG would do.',
      'I checked the preview for a transparent background.',
      'The picture is large enough for where I will use it.',
    ] },
  ],
},
{
  slug: 'how-to-convert-webp-to-jpg',
  title: 'How to Convert Downloaded WebP Images to Standard JPG Photos',
  desc: 'A walkthrough for getting a WebP photo ready for printing or an upload form, including how many pixels a print needs and which quality to pick.',
  date: '2026-10-06', updated: UPDATED, tool: 'webp-to-jpg',
  content: [
    { p: 'A photo counter that prints from a USB stick, an online form that lists JPG as the only accepted type, an older photo editor: all of them have the same answer to a .webp file, which is no. Converting the picture to JPG solves that. This guide covers the two things people usually get wrong along the way, which are the quality setting and the size of the picture itself.' },
    { h: 'Check the pixels before you think about printing' },
    { p: 'The format of a file says nothing about how much detail is in it. A picture saved from a web page is often only 600 to 1200 pixels wide, because that is all a screen needs. A common rule of thumb for sharp photo prints is about 300 pixels for every inch of paper. By that rule, a small 4 by 6 inch print wants roughly 1200 by 1800 pixels. A web picture half that size will still print, but it will look soft. No conversion can change this, so check the pixel dimensions first. You can see them in the details or properties of the file.' },
    { h: 'Worked example: printing a photo a relative posted online' },
    { ol: [
      'Ask for the original first. The copy on a website or social network has been reduced. The photo that is still on the phone of the person who took it is far better.',
      'If the web copy is all there is, save it and check its pixel size.',
      'Open the WebP to JPG tool, choose the file and leave the quality at 90.',
      'Convert, then download the JPG.',
      'Copy it to the USB stick or upload it to the print service, and choose a print size that matches the pixels: small for a small picture.',
    ] },
    { h: 'Worked example: an upload form with a 200 KB limit' },
    { ol: [
      'Convert at quality 80 and read the size in the result list.',
      'If it is above 200 KB, convert again at 70, then at 60 if necessary.',
      'If it is still too large, the picture has too many pixels for that limit. Reduce its dimensions in a photo editor and convert once more.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'Setting the quality to 100 to be safe. The file becomes much larger, and the print or upload does not get visibly better.',
      'Converting a logo or a cut out product picture. JPG fills transparent areas with white and blurs sharp edges slightly. Use PNG for those.',
      'Converting the same picture again and again while trying settings. Always convert from the WebP file, never from a JPG you made earlier.',
      'Blaming the converter for a blurry print. The cause is nearly always too few pixels.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'The printer still rejects the file: some older devices only read baseline JPG files with simple names. Rename the file to something short without special characters, such as photo1.jpg, and try again.',
      'The colours look slightly different in print: screens and printers show colour differently. That is not caused by the conversion.',
      'A white frame appeared around the subject: the WebP had a transparent background. If you need it transparent, convert to PNG instead.',
    ] },
    { h: 'When not to convert to JPG' },
    { p: 'Keep the WebP if the picture will be used on a website. Choose PNG if it has transparency, or if it is a diagram, a logo or a screenshot with text. And if you are still going to edit the picture, do the editing first and make the JPG at the very end, so the picture is compressed only once.' },
    { h: 'Checklist' },
    { ul: [
      'I tried to get the original photo before using a web copy.',
      'I checked the pixel size against the print size or the form requirements.',
      'Quality is around 90 for printing, or as low as the limit of the form requires.',
      'The picture has no transparent background that I need to keep.',
      'I converted from the WebP file and not from an earlier JPG.',
    ] },
  ],
},
{
  slug: 'jpg-vs-png-vs-webp',
  title: 'JPG vs PNG vs WebP: Which Image Format Should You Use?',
  desc: 'A plain comparison of the three common image formats, with a quick way to choose, examples for everyday cases and the mistakes to avoid.',
  date: UPDATED, updated: UPDATED, tool: 'image-compressor',
  content: [
    { p: 'Most questions about image formats come down to three choices. JPG, PNG and WebP can all show the same picture, but they store it in different ways, and each one is good at something the others are not. Picking the right one takes about ten seconds once you know two things: what is in the picture, and where the file is going.' },
    { h: 'The three formats in short' },
    { p: 'JPG, also written JPEG, was designed for photographs. It makes files small by discarding fine detail that the eye barely notices. That is called lossy compression, and how much is discarded depends on the quality setting used when saving. JPG cannot store transparency, and it leaves visible marks around sharp edges such as text.' },
    { p: 'PNG is lossless: it stores every pixel exactly. It supports transparency, and it is very efficient for pictures with large areas of a single colour, such as logos, diagrams and screenshots of software. For photographs it produces very large files, because exact storage of all that fine detail is expensive.' },
    { p: 'WebP is the youngest of the three and was made for the web. It can work in a lossy way like JPG or in a lossless way like PNG, it supports transparency in both, and its files are usually smaller than the JPG or PNG of the same picture. Its weak point is support outside browsers: some editors, office programs and upload forms do not accept it.' },
    { h: 'A quick way to choose' },
    { ul: [
      'A photograph to send, print or upload to a form: JPG.',
      'A logo, an icon, a diagram or a screenshot with text: PNG.',
      'Anything that needs a transparent background and has to open everywhere: PNG.',
      'Any picture that will be shown on a website: WebP, with the original kept as a backup.',
      'A picture you will edit several times: work in PNG, or in the own format of your editor, and export at the end.',
    ] },
    { h: 'Worked example: one picture, three destinations' },
    { p: 'You took a photo of a product on a white table, and you need it in three places.' },
    { ol: [
      'For the online shop, export it from your editor and convert it to WebP at a quality around 80. The page loads faster, and browsers display it without trouble.',
      'For a brochure that a print shop will produce, send a JPG at high quality, or whatever the print shop asks for. Do not send WebP unless they say they accept it.',
      'For a presentation where the product should float on a coloured slide, cut out the background in an editor and save a PNG, because only PNG and WebP can be transparent and presentation software is more certain to accept PNG.',
    ] },
    { p: 'Notice that all three files should be made from the same original, and not from each other. Each lossy conversion costs a little quality, so a chain such as JPG to WebP to JPG ends up worse than either file had to be.' },
    { h: 'Common mistakes' },
    { ul: [
      'Saving photos as PNG. The picture is no better than a high quality JPG, and the file can be several times larger.',
      'Saving screenshots of text as low quality JPG. The letters pick up a grey haze. PNG keeps them clean.',
      'Converting JPG to PNG to improve it. The PNG stores the same pixels, flaws included, in a larger file.',
      'Sending WebP files to people. Not everyone can open them. For email and chat, JPG and PNG are the safe formats.',
      'Deleting originals after converting. Keep the best version of every picture. You can always make a smaller copy later, but never a better one.',
    ] },
    { h: 'What about AVIF, GIF and the rest?' },
    { p: 'AVIF is a newer format than WebP, and it often gives even smaller files, but it takes longer to create and fewer programs open it. It is worth considering for websites and little else for now. GIF is an old format limited to 256 colours. It survives mainly for short animations. ICO is a special container for program icons and website favicons. HEIC is what iPhones use for their own photos, and it usually has to be converted to JPG before other systems accept it.' },
    { h: 'Checklist' },
    { ul: [
      'I know whether my picture is a photo or a graphic.',
      'I know where the file is going and which formats are accepted there.',
      'I need transparency, or I am sure I do not.',
      'I am converting from the original and not from an earlier conversion.',
      'I kept the original file.',
    ] },
  ],
},
{
  slug: 'how-to-create-a-strong-password',
  title: 'How to Create a Strong Password You Can Actually Use',
  desc: 'What makes a password hard to guess, why reuse is the bigger danger, a worked example for securing an email account, and a short checklist.',
  date: '2026-10-05', updated: UPDATED, tool: 'password-generator',
  content: [
    { p: 'Advice about passwords used to be a list of rules: one capital letter, one digit, one symbol. People responded with Password1! and felt safe. Current guidance from security bodies is simpler and works better. Make passwords long, make them random, and never use the same one twice.' },
    { h: 'What strong really means' },
    { p: 'An attacker does not sit and type guesses. Programs try enormous lists of known passwords, common words and predictable patterns, such as a name followed by a year. A password is strong when it is not on any list and follows no pattern. Two things achieve that: length and randomness. Every extra character multiplies the number of possible combinations, so a random password of 16 characters is in a completely different league from one of 8, even if the short one is full of symbols.' },
    { h: 'Reuse is the bigger problem' },
    { p: 'Websites get breached, and when that happens the stolen email and password pairs are tried on other services automatically. If your shopping account and your email share a password, a leak at the shop opens your inbox. A password of average strength that is used on one site only is safer than a brilliant one used on ten.' },
    { h: 'Worked example: securing your main email account' },
    { p: 'Your email account deserves the most care, because the password reset links for all your other accounts arrive there.' },
    { ol: [
      'Open the password generator, set the length to 16 or more and keep numbers and symbols switched on.',
      'Press Generate. The generator leaves out characters that look alike, such as the capital O and the zero, which helps if you ever have to read the password aloud or type it by hand.',
      'Copy the password and save it in a password manager straight away. The manager built into your browser or your phone is fine if you do not have another one.',
      'Change the password in the security settings of your email account, pasting it from the manager.',
      'Turn on two step verification for the account while you are there. Even a stolen password is then not enough to get in.',
      'Sign out and sign in again once, to confirm that the saved password works.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'Small variations of one password, such as Lahore2024 and Lahore2025. Attack tools try such variations first.',
      'Personal facts: names of children, a date of birth, a phone number, a favourite team. These can often be found on social media.',
      'Keeping passwords in a notes app, in an email to yourself or in a chat with yourself. If that one account is opened, everything is.',
      'Sharing a password over chat. If you have to share access, use the sharing feature of the service or of a password manager.',
      'Changing passwords constantly for no reason. That leads to weaker, more predictable choices. Change a password when there is a sign that it leaked, and do it immediately then.',
    ] },
    { h: 'When a random password is the wrong tool' },
    { p: 'A few passwords have to live in your head: the one that unlocks your computer, and the master password of your password manager. A random string is miserable to memorise and to type. Use a passphrase instead, meaning four or five unrelated words in a row. It is long and easy to remember, and it is strong as long as the words are truly unrelated and are not a quotation or a song line. For everything else, let the generator and the manager do the work.' },
    { h: 'If you think a password has leaked' },
    { ul: [
      'Change it on that service at once, and on any other service where you used the same one.',
      'Check the recent sign in activity of the account, and sign out all other devices if the service offers that.',
      'Check that the recovery email address and phone number are still yours.',
    ] },
    { h: 'Checklist' },
    { ul: [
      'Each important account has its own password.',
      'Passwords are at least 12 characters long, and 16 or more where the site allows it.',
      'They are stored in a password manager, not in notes or messages.',
      'Two step verification is on for email, banking and social accounts.',
      'The few passwords I must remember are passphrases.',
    ] },
  ],
},
{
  slug: 'how-to-sign-pdf-documents-online',
  title: 'How to Sign PDF Documents on a Phone or Computer',
  desc: 'How to add your signature to a PDF without printing, what kind of signature that is, a worked example on a phone, and when it is not enough.',
  date: '2026-10-06', updated: UPDATED, tool: 'sign-pdf',
  content: [
    { p: 'The old routine was to print the document, sign it, scan it and email it back. That takes a printer, a scanner and patience. Placing a picture of your signature straight onto the PDF gets the same result in a couple of minutes. Before you rely on it, though, it helps to know what kind of signature this is.' },
    { h: 'Two different things are called a signature' },
    { p: 'The first is a picture of your handwritten signature placed on the page. It is the digital version of signing with a pen. It shows your agreement, and people accept it for many everyday purposes, such as rental forms, internal approvals, permission slips and quotations.' },
    { p: 'The second is a certificate based digital signature. It uses a cryptographic certificate issued to you. It proves who signed, and it shows whether the document was changed afterwards. Some banks, courts, tax authorities and government portals require this kind. The DocBrio tool creates the first kind. It cannot create the second. Which one is valid for your document depends on the law of your country and on what the receiver accepts, so when the document matters, ask them.' },
    { h: 'Worked example: signing a rental agreement on a phone' },
    { ol: [
      'Read the whole agreement before anything else. A signature means that you have.',
      'Open the Sign PDF tool on your phone and choose the PDF.',
      'Draw your signature with a finger. Turn the phone sideways for more room, and try again until it looks like your normal signature.',
      'Go to the page with the signature line and tap where the signature belongs. Drag it into place, and drag its corner until it is about as tall as the printed text around it.',
      'If the form asks for a date or your printed name, add them as text next to the signature.',
      'Save the signed PDF and open it once. Check that the signature is on the right page and does not cover any text.',
      'Send the signed copy, and keep one for yourself.',
    ] },
    { h: 'Common mistakes' },
    { ul: [
      'A signature that is much too large. It looks careless and can hide part of the text. Match the size of a handwritten one.',
      'Signing only the last page when every page needs initials. Read the instructions on the document.',
      'Typing your name in an ordinary font and calling it a signature. Some receivers reject that. A drawn signature is closer to what they expect.',
      'Signing something you have not read, because it is quick on a phone.',
      'Sending a photo of the screen instead of the saved PDF.',
    ] },
    { h: 'Troubleshooting' },
    { ul: [
      'The signature looks shaky: draw it larger and more slowly, and then make it smaller on the page. Shrinking smooths small wobbles. A stylus helps as well.',
      'The PDF will not open: it may be password protected or locked against changes. Ask the sender for an unlocked copy.',
      'The receiver says it is not valid: they probably need a certificate based signature or a signature on paper. Ask which method they accept.',
    ] },
    { h: 'When this method is not enough' },
    { p: 'Do not rely on a drawn signature for documents that have to be notarised or witnessed, for property transfers, for court filings or wherever an authority names a specific signing system. In those cases the form of the signature is part of the legal requirement. If you are unsure, ask the receiver or a lawyer. This guide is general information and not legal advice.' },
    { h: 'Keep your signature safe' },
    { p: 'A picture of your signature can be copied by anyone who has a file containing it. Send signed documents only to the people who need them, and do not post them publicly. In the DocBrio tool your signature stays in the browser and is not saved by the site, so you draw it again next time.' },
    { h: 'Checklist' },
    { ul: [
      'I read the whole document.',
      'I know that a drawn signature is acceptable for this purpose.',
      'The signature is on the correct page, at a natural size, and covers no text.',
      'Date, name and initials are added where the form asks for them.',
      'I saved a copy of the signed PDF for my records.',
    ] },
  ],
},
];
