// Page text for the 13 image tools. Every statement about what a tool does matches components/ImageConvert.js
// and the ImageCompressor in components/ToolClient.js: change the text here when that code changes.
// about: paragraphs. links: [tool slug, why it is relevant]. guide: [guide slug, link text].
export const imagePages = {
'image-compressor': {
  title: 'Image Compressor: Make JPG and PNG Files Smaller',
  desc: 'Make a photo or screenshot smaller by saving it as a JPG at the quality you choose. Works in your browser and the image is not uploaded.',
  about: [
    'A photo from a modern phone is often several megabytes, while the form you need to send it through may accept only a fraction of that. This tool saves your picture again as a JPG at the quality you pick and shows the size before and after, so you can judge the result instead of guessing.',
    'JPG compression is lossy. It makes a file smaller by throwing away fine detail that the eye is least likely to miss, and the quality number decides how much is thrown away. A lower number gives a smaller file, but past a certain point you start to see blocky patches, smeared textures and faint halos around sharp edges. The detail that was removed cannot be brought back later, so always keep your original file.',
    'Good values depend on what is in the picture. For photographs of people, places and products, a quality between 60 and 80 is usually hard to tell apart from the original at normal viewing size. Screenshots and scanned documents are different: letters have hard edges, and those show compression marks much sooner. For anything with text, stay around 80 to 90 and read the small print in the preview before you download.',
    'Many upload forms set a limit such as 100 KB, 200 KB or 500 KB. A simple way to reach one: compress at 70, look at the After size, and lower the slider ten points at a time until you are under the limit. If the picture already looks rough and is still too big, the problem is no longer the quality setting. The image simply has too many pixels.',
    'File size depends on the number of pixels as much as on quality. Halving both the width and the height leaves only a quarter of the pixels, which shrinks the file far more than a few points on the slider. This tool keeps the width and height as they are, so for a tight limit, first make the picture smaller in your phone gallery editor or in Paint or Photos on Windows, then compress it here.',
    'PNG files need a separate note. PNG is lossless and has no quality setting, which is why a PNG cannot be made much smaller by quality alone. When you give this tool a PNG, it converts it to JPG. For photos and busy screenshots that saves a lot of space. For simple graphics with a few flat colours, PNG is often already the smaller format, and the tool will show you when the result is not smaller so you can keep the original.',
  ],
  when: 'Use it when a form, an email or a chat app refuses a picture because it is too large, or when you want the photos on a web page to load faster. It suits photographs and scanned pages best. For logos, icons and drawings with flat colours or a transparent background, keep the PNG or convert it to WebP instead.',
  limits: 'It handles one image at a time and the output is always a JPG, so transparent areas turn white. The width and height are not changed, which means a very large photo can stay above a tight limit even at low quality. Details stored inside the original file, such as the date and the location where a photo was taken, are not copied to the new file.',
  how: [
    'Choose one image. JPG, PNG, WebP and any other type your browser can display will work.',
    'Leave the quality at 70 or move the slider. Lower means a smaller file.',
    'Press Compress and compare the Before and After sizes under the button.',
    'Look at the preview. If faces or text look rough, raise the quality and press Compress again.',
    'Download the result. It is saved with _compressed.jpg at the end of the name, so your original is not replaced.',
  ],
  faq: [
    ['Why is the result a JPG even when I upload a PNG?', 'The tool reduces size by using JPG compression, and PNG has no quality setting to lower. If you need to keep a transparent background, use PNG to WebP instead.'],
    ['My file is still above the upload limit. What can I do?', 'Lower the quality in steps of ten. If the picture looks bad before it gets under the limit, make its width and height smaller in a photo editor first and then compress it again. A form photo rarely needs as many pixels as a phone camera produces.'],
    ['Can I get the original quality back from the compressed file?', 'No. The removed detail is gone for good. Keep the original and treat the compressed file as a copy for sending.'],
    ['Why did my file get bigger instead of smaller?', 'This happens when the original is a JPG that was already compressed harder than your slider setting, or a simple PNG graphic that PNG stores very efficiently. Lower the quality, or keep the original.'],
    ['Does compressing change the width and height of my picture?', 'No. The picture keeps the same number of pixels. Only the amount of detail stored for them changes.'],
  ],
  links: [
    ['png-to-jpg', 'converts several PNG screenshots in one go'],
    ['jpg-to-webp', 'gives smaller files when the photos are for a website'],
    ['png-to-webp', 'makes a PNG lighter without losing its transparent background'],
  ],
  guide: ['reduce-image-size-without-losing-quality', 'How to get an image under an upload limit'],
},

'webp-to-png': {
  title: 'WebP to PNG Converter: Open WebP Images Anywhere',
  desc: 'Convert WebP images saved from websites into PNG files that open in any program. Transparency is kept. Free, and nothing is uploaded.',
  about: [
    'You right click a picture on a website, choose Save image, and the file that lands in your Downloads folder ends in .webp. Then the program you wanted to use it in says the file type is not supported. This converter turns that file into a PNG, which practically every image program can open.',
    'The picture arrived as WebP because of how websites deliver images today. WebP was created by Google to make web pages lighter, and many sites and image delivery networks automatically send a WebP version to any browser that can display it, even when the person who uploaded the picture used a JPG or a PNG. Your browser saves exactly what it received.',
    'Every current browser shows WebP, but support outside browsers arrived more slowly. Older versions of photo editors and office programs, some printing kiosks and many upload forms still expect JPG or PNG only. That gap is the reason a file that looks fine in a browser tab will not open elsewhere.',
    'PNG is the safe choice for the conversion because it is lossless. Every pixel your browser decodes from the WebP file is stored exactly as it is, so the conversion adds no new quality loss. It cannot put back detail that the WebP file had already lost, but it will not make the picture any worse. Transparent areas are kept too, which matters for logos, stickers and product cut outs that need to sit on a coloured background.',
    'The price is file size. A PNG is often several times larger than the WebP it came from, especially for photographs. The result list shows both sizes for every file. When you do not need transparency and the size matters, for example for an email attachment, converting to JPG is the better route.',
    'One more thing to know: WebP files can be animated, a little like GIFs. This tool saves a single still picture, so an animated WebP comes out as one frame.',
    'You can pick several WebP files in one go. They are converted one after another on your device, each one is listed with a preview, and a ZIP download collects them into a single file. Apart from the format nothing about the picture changes: the width and the height stay the same.',
  ],
  when: 'Use it when a WebP file will not open in your editor, cannot be inserted into a document, or is rejected by an upload form, and you want an exact copy with the transparent background intact. It is also the right choice before editing, because saving a PNG again and again does not wear the picture down.',
  limits: 'Animated WebP files become a single still image. The PNG will usually be larger than the WebP, sometimes much larger. Details stored inside the original file, such as camera information, are not carried over. Your browser has to be able to display WebP, which all current browsers can.',
  how: [
    'Choose one or more WebP files, or drag them onto the box.',
    'Press Convert to PNG. There is no quality setting because PNG keeps every pixel.',
    'Check the list: each row shows a preview and the size before and after.',
    'Download the files one by one, or press Download all as ZIP when you converted several.',
  ],
  faq: [
    ['Why did my image save as WebP in the first place?', 'Many websites send pictures as WebP because the files are smaller and pages load faster. Your browser saves the file in the format the site sent, whatever format the original upload was.'],
    ['Is any quality lost when converting WebP to PNG?', 'No new quality is lost, because PNG stores the decoded picture exactly. Detail that the WebP file had already lost stays lost.'],
    ['Why is the PNG so much bigger than the WebP?', 'WebP usually throws away some detail to stay small, and PNG is not allowed to. Storing every pixel exactly takes more space, most of all for photos.'],
    ['Can I just rename the file from .webp to .png?', 'No. Renaming changes only the name, not the data inside. Some programs will then refuse the file or show an error. The picture has to be decoded and saved again, which is what this tool does.'],
    ['What happens to an animated WebP?', 'You get one still picture. The animation is not kept.'],
  ],
  links: [
    ['webp-to-jpg', 'gives a much smaller file when you do not need transparency'],
    ['png-to-webp', 'goes the other way when you need a light file for a website again'],
  ],
  guide: ['how-to-convert-webp-to-png', 'Why saved web images arrive as WebP and how to deal with them'],
},

'webp-to-jpg': {
  title: 'WebP to JPG Converter: For Printing and Uploads',
  desc: 'Turn WebP images into JPG files for printing, upload forms and older software. Choose the quality yourself. Runs in your browser.',
  about: [
    'JPG is still the format that the widest range of things accept: photo printing counters and print shop websites, online application forms, older photo editors, digital photo frames and televisions that show pictures from a USB stick. When one of them rejects a .webp file, converting it to JPG is the usual fix.',
    'JPG cannot store transparency. If your WebP image has a transparent background, this tool places it on white before saving. For a photo that changes nothing. For a logo that was made to sit on a coloured background, you will get a white box around it, and in that case PNG is the format you want instead.',
    'The quality slider starts at 90. For printing, stay between 85 and 95 so the print shop has as much detail as possible to work with. For forms with a small size limit, 70 to 80 is normally enough for a clear picture. Setting the slider to 100 makes the file a great deal larger for a gain that is very hard to see.',
    'It helps to know that most WebP pictures on the web are already compressed in a lossy way. Saving one as a JPG compresses it a second time, and every lossy step leaves its own small marks. At a high quality setting you will not notice them. What you should avoid is converting back and forth between formats, because the marks add up. Convert once, from the best copy you have.',
    'Compared with PNG, a JPG of a photograph is usually a fraction of the size, which is why JPG is the better target whenever the picture is a photo and the file has to travel by email or through a form.',
    'The width and height of the picture stay as they are, and you can convert a whole batch of files in one run and collect them as a ZIP file. That is useful when a print service wants twenty holiday photos at once.',
    'A note for printing: a picture saved from a website is often only a few hundred pixels wide, because that is all a web page needs. Converting the format does not add pixels. If a print comes out soft or blocky, the cause is nearly always the small size of the web image and not the conversion.',
  ],
  when: 'Use it when a WebP photo has to go to a printer, into an application form, into older software or onto a device that only reads JPG. Choose WebP to PNG instead when the image has a transparent background you need to keep, or when it is a logo or drawing with sharp edges.',
  limits: 'Transparent areas become white. The picture is compressed again, so a very small amount of detail is lost on top of what the WebP had already lost. Animated WebP files become one still image, and information stored in the file such as camera details is not copied.',
  how: [
    'Choose the WebP images you want to convert.',
    'Set the quality: around 90 for printing, 70 to 80 when a form limits the file size.',
    'Press Convert to JPG.',
    'Compare the sizes in the list. If a file is still too large for your form, lower the quality and convert again.',
    'Download each JPG, or all of them together as a ZIP file.',
  ],
  faq: [
    ['Does converting WebP to JPG lose quality?', 'A little, because JPG compresses the picture again. At 90 the difference is very hard to see. It becomes visible when you choose a low quality or convert the same picture several times.'],
    ['Why does my image have a white background now?', 'JPG has no transparency, so transparent areas are filled with white. Use WebP to PNG if you need the background to stay transparent.'],
    ['Which quality should I choose for printing?', 'Between 85 and 95. Higher than that mostly makes the file bigger without a visible improvement.'],
    ['Is JPG different from JPEG?', 'No. They are two spellings of the same format. This tool saves files with the .jpg ending, which every program that reads JPEG also accepts.'],
    ['My print looks blurry. Did the conversion cause that?', 'Probably not. Pictures saved from websites are often small, and a small picture stretched over a large print looks soft. The conversion keeps the same number of pixels and does not add or remove any.'],
  ],
  links: [
    ['webp-to-png', 'keeps transparent backgrounds and sharp logo edges'],
    ['image-compressor', 'pushes a single JPG further down when a form has a strict limit'],
    ['jpg-to-webp', 'converts back when a photo is going onto a web page'],
  ],
  guide: ['how-to-convert-webp-to-jpg', 'Getting a WebP picture ready for printing or a form'],
},

'png-to-webp': {
  title: 'PNG to WebP Converter: Smaller Images for Websites',
  desc: 'Convert PNG images to WebP to make web pages lighter. Transparency is kept and you choose the quality. The files stay on your device.',
  about: [
    'Images are usually the heaviest part of a web page, and PNG is the heaviest of the common image formats. WebP was designed for the web and can replace PNG in most places on a site, because it supports transparent backgrounds too. That makes it a good fit for logos, interface graphics, illustrations and screenshots.',
    'WebP has two ways of working. Lossless WebP keeps every pixel exactly, like PNG does, and is normally somewhat smaller than the PNG. Lossy WebP throws away fine detail in the way JPG does, but unlike JPG it can still keep transparency, and it gives much smaller files. This tool uses the quality slider, which controls the lossy kind. The slider starts at 85.',
    'The right setting depends on the picture. For screenshots and interface graphics with small text, use 90 or more so the letters stay crisp. For photographs that happen to be stored as PNG, 75 to 85 is a sensible range. For flat logos, zoom in on the edges of the result and raise the quality if you see fuzz around them.',
    'The conversion does not resize anything. If a screenshot is 3000 pixels wide and your page shows it at 800, resize it before you convert it, because removing pixels nobody sees saves more than any change of format.',
    'Converting is not always a good idea. WebP is a format for browsers. If the file is going to a client by email, into a Word or PowerPoint document, to a print shop or through an upload form, the person or program at the other end may not be able to open it. For those uses, keep the PNG.',
    'Treat the PNG as your master copy and the WebP as the copy you publish. If you later need a different quality or want to edit the picture, go back to the PNG. Converting a lossy WebP again would stack a second round of loss on top of the first.',
    'On the website itself, a WebP file works in an ordinary image tag in all current browsers. Most site builders and content management systems accept WebP uploads today, but it is worth checking yours before you convert a whole folder.',
  ],
  when: 'Use it for pictures that will be shown on a website or in a web app, especially large PNG graphics and screenshots that slow a page down. It is not the right tool for files you plan to email, print or archive.',
  limits: 'The slider controls lossy compression, and what a browser does at exactly 100 differs from browser to browser, so do not rely on this tool when you need a guaranteed pixel exact WebP. Simple graphics that are already tiny as PNG may hardly shrink at all. In Safari the tool has to download a small WebP encoder first, which needs an internet connection.',
  how: [
    'Choose the PNG files you want on your website.',
    'Set the quality: 90 or more for screenshots with text, around 80 for photos.',
    'Press Convert to WebP.',
    'Read the before and after sizes in the list, and look closely at edges and small text in the previews.',
    'Download the WebP files and upload them to your site. Keep the PNG originals somewhere safe.',
  ],
  faq: [
    ['How much smaller will the WebP file be?', 'It depends on the picture. Photos and detailed screenshots stored as PNG often shrink a great deal. Simple graphics with a few flat colours are already small as PNG and may gain little. The tool shows both sizes so you can decide for each file.'],
    ['Is the transparent background kept?', 'Yes. WebP supports transparency and the tool keeps it.'],
    ['Does this tool create lossless WebP?', 'The slider controls lossy compression. A setting of 100 keeps the picture very close to the original, but we do not promise a pixel exact lossless file.'],
    ['Can all browsers show WebP?', 'Current versions of Chrome, Edge, Firefox and Safari can. Very old browsers such as Internet Explorer cannot.'],
    ['Will WebP images improve my Google ranking?', 'Smaller images make pages load faster, and speed is one of many things search engines look at. Nobody can promise a ranking change from converting images alone.'],
  ],
  links: [
    ['jpg-to-webp', 'does the same job for photos that are stored as JPG'],
    ['png-to-avif', 'can give even smaller files, at the cost of slower conversion'],
    ['webp-to-png', 'turns a WebP back into a PNG when someone cannot open it'],
  ],
  guide: ['how-to-convert-png-to-webp-for-speed', 'Preparing PNG graphics for a faster website'],
},

'jpg-to-webp': {
  title: 'JPG to WebP Converter: Lighter Photos for the Web',
  desc: 'Convert JPG photos to WebP for faster web pages. See the size before and after for each photo. No upload, no signup.',
  about: [
    'Before converting, ask one question: is this photo going onto a website? If the answer is yes, WebP is worth trying. If the photo is for email, WhatsApp, printing or an application form, stay with JPG, because that is what those places expect.',
    'WebP generally stores a photograph in fewer bytes than JPG at a similar visible quality. On a page with many photos, such as a blog post, a shop category or a gallery, the saving adds up, and visitors on mobile data notice it most.',
    'There is a catch that many guides skip. A JPG is already a lossy file. Converting it means decoding it and compressing it again with a different method, and each lossy step adds its own small errors. The second step also spends part of the file faithfully preserving the marks left by the first one. At a high quality setting you will not see any of this. At a low setting you get smeared textures in hair and grass, and visible steps of colour in skies.',
    'Two habits keep the result clean. First, start from the best version of the photo you have, such as the camera original or a high quality export from your editor, and not a copy that has been forwarded through a chat app. Second, leave the slider near its starting value of 85, or within 75 to 85, and compare the result with the original at full size. Skin, sky and any text in the picture are the places where problems show first.',
    'Sometimes the WebP is not smaller. This happens when the JPG was already compressed hard: at 85 the new file can come out the same size or even larger. The result list shows the size before and after for each photo. Where there is no real gain, keep using the JPG.',
    'The pixel dimensions are left alone as well. A photo straight from a camera is usually far wider than any web page displays it, so resize it to its display width first and convert it afterwards.',
    'Finally, check where the file will be opened. Current browsers display WebP, and most website builders accept it, but some email programs and older desktop software do not. Keep the JPG originals so you always have a version that opens everywhere.',
  ],
  when: 'Use it when you are preparing photos for a web page and want them to load faster. Do not use it for photos you will send to people, print or upload to forms. JPG is the safer format for all of those.',
  limits: 'The photo is compressed a second time, so quality can only stay the same or get slightly worse, never better. An already small JPG may not shrink further. Camera details and location stored in the JPG are not copied into the WebP file. In Safari a small WebP encoder is downloaded first.',
  how: [
    'Choose the JPG photos you plan to publish.',
    'Keep the quality at 85, or lower it a little for large background photos.',
    'Press Convert to WebP.',
    'Compare the sizes. Keep the WebP only for photos where it is clearly smaller.',
    'Download the files and upload them to your site. Keep the JPG originals.',
  ],
  faq: [
    ['Is WebP always smaller than JPG?', 'No. It usually is for photos saved at high quality, but a JPG that is already heavily compressed can come out the same size or larger. The tool shows both sizes so you can check.'],
    ['What quality should I use?', 'Start at 85. Go down toward 75 for large photos where fine detail matters less, and compare the result with the original before you publish it.'],
    ['Should I delete my JPG files after converting?', 'No. Keep them. They are your originals, they open everywhere, and you will need them if you want a different quality later.'],
    ['Does the WebP keep the camera and location data from my photo?', 'No. That information is not copied to the new file. This is useful for privacy, but keep the JPG if you need the data.'],
    ['What about visitors with very old browsers?', 'All current browsers show WebP. If you have to support very old ones, your site can offer the JPG as a fallback next to the WebP.'],
  ],
  links: [
    ['png-to-webp', 'handles graphics and screenshots with transparency'],
    ['webp-to-jpg', 'converts a WebP back when someone needs a normal photo file'],
    ['image-compressor', 'makes a JPG smaller while keeping it a JPG'],
  ],
  guide: ['how-to-convert-jpg-to-webp', 'When converting photos to WebP is worth it'],
},

'jpg-to-png': {
  title: 'JPG to PNG Converter: When You Really Need PNG',
  desc: 'Convert JPG to PNG for editing or for uploads that require PNG. It does not improve quality and the file gets bigger. Runs in your browser.',
  about: [
    'First, the honest part. Converting a JPG to a PNG does not make the picture sharper or restore anything. The PNG stores exactly the pixels the JPG shows, including any blocky patches or soft edges that JPG compression left behind. The file also gets bigger, often several times bigger, because PNG has to record every pixel exactly.',
    'To give a rough idea of the change in size: in our own test, a small JPG of about 5 KB became a PNG of about 42 KB. Your numbers will differ, but an increase of several times is normal for photos.',
    'So why convert at all? There are four situations where a PNG is really what you need.',
    'One: a website, a printing service or a piece of software accepts only PNG. The converted file is a perfectly valid PNG and will be accepted.',
    'Two: you are going to edit the picture and save it many times. Every time a JPG is saved, it is compressed again and loses a little more. A PNG can be saved as often as you like without further loss, so converting once at the start stops the damage from building up.',
    'Three: you are adding text, a logo or other sharp elements on top of a photo. Those new edges stay clean in a PNG, while a JPG would blur them slightly.',
    'Four: you plan to cut out the background later. JPG cannot hold transparency at all, so the picture has to be in a format like PNG before an editor can make parts of it transparent.',
    'That last point causes a common misunderstanding. The conversion itself does not remove the background. A JPG has a solid picture from edge to edge, and the PNG you get has the same solid picture. Making the background transparent is a separate editing step in a photo editor or a background remover.',
    'When should you not convert? When the goal is better quality, a smaller file or an image for a web page. In all three cases the JPG you already have is the better file. And when you finish editing a PNG and want to send it to someone, exporting a JPG copy for sharing will save them a large download.',
  ],
  when: 'Use it when something specifically demands a PNG file, or as a first step before repeated editing, adding sharp overlays or cutting out a background. If you only want the picture to look better or the file to be smaller, this conversion will not help.',
  limits: 'Quality is not improved and lost detail does not come back. The PNG is usually several times larger than the JPG. The background stays solid. Camera details and location stored in the JPG are not copied to the PNG.',
  how: [
    'Choose one or more JPG files.',
    'Press Convert to PNG. There is nothing to set, because PNG keeps every pixel as it is.',
    'Look at the sizes in the list so the larger file does not surprise you.',
    'Download the PNG and open it in your editor, or upload it where a PNG was required.',
  ],
  faq: [
    ['Does converting JPG to PNG improve the quality?', 'No. The PNG is an exact copy of what the JPG shows. Nothing is added and nothing is repaired.'],
    ['Why is the PNG so much larger than my JPG?', 'JPG saves space by discarding detail. PNG is not allowed to discard anything, so it needs more space for the same picture, and photos are the hardest case for it.'],
    ['Will the background become transparent?', 'No. A JPG has no transparent areas, so the PNG has the same solid background. You can remove the background afterwards in an image editor.'],
    ['A site only accepts PNG. Will a converted JPG be accepted?', 'Yes. The result is a normal PNG file. Check the size limit of the site though, because the PNG will be larger than your JPG.'],
    ['Can I turn the PNG back into a JPG later?', 'Yes, with PNG to JPG. Remember that saving as JPG compresses the picture again, so do it once at the end of your editing and not after every change.'],
  ],
  links: [
    ['png-to-jpg', 'makes a small JPG copy again when you have finished editing'],
    ['image-compressor', 'is what you want if the real goal is a smaller file'],
  ],
  guide: ['jpg-vs-png-vs-webp', 'JPG, PNG or WebP: which format fits which job'],
},

'png-to-jpg': {
  title: 'PNG to JPG Converter: Shrink Large Screenshots',
  desc: 'Convert PNG screenshots and photos to much smaller JPG files. Transparent areas become white. Convert several at once in your browser.',
  about: [
    'Windows, macOS and most phones save screenshots as PNG. That is a sensible default, because PNG keeps text perfectly sharp, but a full screen capture of a page full of photos can easily be several megabytes. Converting it to JPG is the quickest way to get a file you can attach or upload.',
    'The saving comes from how the two formats work. PNG has to keep every pixel exactly. JPG is allowed to approximate, and photo like content can be approximated very well. A screenshot of a video, a map or a web page with pictures will shrink a lot. A screenshot of mostly plain interface, such as a settings window or a spreadsheet, may already be small as a PNG and gain little, and its text can pick up a slight fuzz. The list shows both sizes, so check before you swap the files.',
    'JPG has no transparency. Transparent parts of your PNG are filled with white. For most pictures that is exactly what you would expect. Watch out for one case: a white or very light logo on a transparent background will seem to vanish, because it is now white on white. Such a logo should stay a PNG.',
    'Job portals, university admission forms and other online application systems often ask for a JPG below a stated size. A routine that works: convert at 90 and read the size. If it is over the limit, try 75, then 60. If the picture is still too big at 60, it has more pixels than the form needs, and you should crop it or reduce its width and height first.',
    'Some advice on the slider. At 90, photos are very hard to tell apart from the original. For screenshots with text, do not go below about 85, or you will see faint shadows around the letters. Settings under 60 are for cases where size matters more than looks. A setting of 100 mostly makes the file larger.',
    'You can select many screenshots together, convert them in one run and download them as a single ZIP file, which is handy after a long session of capturing.',
  ],
  when: 'Use it when PNG screenshots or photos are too large to email or upload, or when a form accepts only JPG. Keep the PNG when the picture has a transparent background you need, or when it is a diagram or logo whose edges must stay perfectly sharp.',
  limits: 'Transparent areas turn white. JPG removes some detail for good, so keep the PNG if you may need to edit the picture later. Simple graphics may not get much smaller. The width and height are not changed.',
  how: [
    'Choose one or more PNG files.',
    'Leave the quality at 90, or lower it if you have a size limit to meet.',
    'Press Convert to JPG.',
    'Check each row in the list for the size before and after, and look at the preview for fuzzy text.',
    'Download the files one at a time or all together as a ZIP file.',
  ],
  faq: [
    ['What happens to transparent areas of my PNG?', 'They are filled with white, because JPG cannot store transparency.'],
    ['My white logo disappeared after converting. Why?', 'The transparent background became white, so a white logo no longer stands out. Keep such a logo as PNG, or place it on a coloured background in an editor before converting.'],
    ['Why does the text in my screenshot look fuzzy?', 'JPG compression leaves faint marks around hard edges such as letters. Raise the quality to 90 or more, or keep the screenshot as PNG if the text has to be perfectly clean.'],
    ['Why is the JPG hardly smaller than the PNG?', 'Pictures with large flat areas and few colours are stored very efficiently by PNG already. JPG mainly helps with photos and detailed images.'],
    ['Can I convert many screenshots in one go?', 'Yes. Select as many as you like. They are converted one after another on your device, and you can download them together as a ZIP file.'],
  ],
  links: [
    ['image-compressor', 'squeezes a single picture further for a strict upload limit'],
    ['png-to-webp', 'keeps transparency while still making the file much smaller'],
    ['jpg-to-png', 'goes back to PNG when you need to edit again'],
  ],
  guide: ['how-to-convert-png-to-jpg', 'Getting screenshots under a form or email size limit'],
},

'ico-to-png': {
  title: 'ICO to PNG Converter: Extract an Icon as PNG',
  desc: 'Open an .ico file and save the largest icon inside it as a PNG with its transparent background. Works in your browser, no upload.',
  about: [
    'ICO is the icon format of Windows, and it is also the format of the classic favicon.ico file that websites use for the small picture in a browser tab. An ICO file is not a single picture. It is a container: a short list at the start of the file, followed by the same icon stored at several sizes, for example 16, 32, 48 and 256 pixels. Windows or the browser picks whichever size fits the place where the icon is shown.',
    'That design is practical for the system and awkward for people. Phone galleries, many photo editors and most upload forms do not open .ico files, so you cannot simply look at one, edit it or put it in a document.',
    'There are a few everyday reasons to pull the picture out. The original artwork of a logo has been lost and the favicon is the only copy left. You are writing a tutorial or a manual and want to show a program icon in it. You are redesigning an old application and need the current icon as a starting point. Or you just want to see what a downloaded icon looks like.',
    'This tool reads the list inside the file and takes the widest image. If two entries have the same width, it takes the one with more colours. That image is saved as a PNG at its own size, with no enlarging. If the largest icon in the file is 48 by 48 pixels, you get a PNG of 48 by 48 pixels.',
    'PNG is the natural target for an icon. It keeps the transparent background and stores flat colours and sharp edges exactly. In fact, many modern ICO files already store their largest size as PNG data on the inside.',
    'If you are not sure whether a file is really an icon, the result will tell you. A real ICO file converts and shows a preview. A file that only has the .ico ending, such as an error page that was saved under that name, gives a message that it could not be opened.',
    'A reminder about rights: the icons and logos of other companies are normally protected by copyright or trademark. Extracting your own icons, or looking at an icon for reference, is fine. Reusing somebody else\'s logo as your own is not.',
  ],
  when: 'Use it when you need the picture from a favicon or a Windows icon as a normal image: to edit it, to place it in a document or a design, or to view it on a device that does not open .ico files.',
  limits: 'Only the largest image in the file is extracted, and the smaller sizes are not offered separately. The tool does not enlarge anything, so an ICO that holds only 16 or 32 pixel icons gives a very small PNG. Damaged or unusual icon files may fail to open, in which case you will see a message saying so.',
  how: [
    'Choose your .ico file. On a phone, the file picker may list all images, so pick the icon file by its name.',
    'Press Convert to PNG.',
    'Look at the preview and the size in the result row.',
    'Download the PNG. It keeps the transparent background of the icon.',
  ],
  faq: [
    ['Which size do I get from the ICO file?', 'The largest one stored in the file. If the file holds 16, 32 and 256 pixel versions, you get the 256 pixel one.'],
    ['Can I extract the other sizes too?', 'Not with this tool. It always takes the largest image. You can make smaller copies from that PNG in any image editor.'],
    ['The PNG is tiny and looks blurry when I enlarge it. Can that be fixed?', 'No. Some ICO files contain only very small icons, and enlarging a small picture cannot add detail. You would need the original artwork.'],
    ['Is a favicon.ico file a normal ICO file?', 'Yes. It is an ordinary ICO file that happens to be named favicon, and it converts in the same way.'],
    ['Is the transparent background of the icon kept?', 'Yes. PNG supports transparency, so the icon keeps its shape with nothing added around it.'],
  ],
  links: [
    ['png-to-ico', 'packs your edited PNG back into an .ico file'],
    ['ico-to-jpg', 'is an option when the place you need the icon accepts only JPG'],
  ],
  guide: ['how-to-convert-ico-to-png', 'What is inside an ICO file and how to get the picture out'],
},

'ico-to-jpg': {
  title: 'ICO to JPG Converter: Use an Icon in Documents',
  desc: 'Convert an .ico icon to a JPG for documents, slides and email signatures. The transparent background becomes white. No upload needed.',
  about: [
    'Sometimes an icon has to go somewhere that only understands ordinary pictures: a user manual written in Word, a PowerPoint slide, an email signature, a support ticket or a web form. An .ico file will be refused in most of those places, and a JPG will not.',
    'The tool does three things. It finds the largest image stored inside the .ico file. It places that image on a white background. Then it saves the result as a JPG at the quality you choose, starting at 90.',
    'The white background needs a little thought. Nearly every icon has a transparent area around its shape, and JPG cannot store transparency. On a white page you will not notice the difference. On a coloured slide or in an email signature with a dark background, the icon will sit inside a visible white square. If that is your situation, convert to PNG instead, because PNG keeps the transparent surround.',
    'The second thing to know is size. Icons are small pictures, typically between 16 and 256 pixels wide. This tool does not enlarge them. If you then stretch a 32 pixel icon across half a slide, it will look blurry or blocky, and no converter can prevent that. As a rule, show an icon at its own pixel size or smaller. If the file holds only tiny sizes and you need a big picture, look for the original artwork.',
    'If you can choose between icon files, take the one from the newest version of the program. Older icons were often drawn at 32 or 48 pixels only, while newer ones usually include a 256 pixel version that still looks clean in a printed manual.',
    'It is also fair to say that JPG is not the ideal format for icons. Icons are made of flat colours and hard edges, which is exactly the kind of picture that JPG handles worst. At low quality you will see faint smudges around the edges. Keep the slider at 90 or above, and choose JPG only when the destination insists on it.',
    'The good news is that the file will be tiny. A JPG made from an icon is normally just a few kilobytes, which suits email signatures and forms with strict limits.',
  ],
  when: 'Use it when a document editor, an email program or an upload form accepts JPG but not ICO or PNG, and the icon will be shown on a white or light background.',
  limits: 'The transparent area around the icon becomes white. The picture is as small as the largest icon in the file and will look blurry if you enlarge it. Flat icon artwork can show faint JPG marks around its edges at lower quality settings.',
  how: [
    'Choose the .ico file.',
    'Keep the quality at 90 or higher. Icons have sharp edges that suffer at low quality.',
    'Press Convert to JPG.',
    'Download the JPG and insert it into your document or signature at its original size.',
  ],
  faq: [
    ['Why is the background white and not transparent?', 'Icons usually have a transparent surround and JPG cannot store transparency, so the tool fills it with white. Use ICO to PNG to keep it transparent.'],
    ['Why does the icon look blurry in my document?', 'It is probably being shown larger than it really is. Icons are small images, often only 32 or 48 pixels wide. Reduce its size in the document, or find a larger source.'],
    ['Should I choose JPG or PNG for an icon?', 'PNG, whenever the destination accepts it. PNG keeps transparency and sharp edges. Pick JPG only when PNG is not allowed.'],
    ['Which quality setting works best for icons?', '90 or higher. The file stays very small anyway, so there is little to gain from lowering it.'],
  ],
  links: [
    ['ico-to-png', 'keeps the transparent background and gives cleaner edges'],
    ['jpg-to-ico', 'does the reverse and builds an icon from a JPG'],
  ],
  guide: ['how-to-convert-ico-to-jpg', 'Putting an icon into a document or email signature'],
},

'png-to-ico': {
  title: 'PNG to ICO Converter: Make a Favicon from a Logo',
  desc: 'Turn a PNG logo into a favicon.ico with sizes from 16 to 256 pixels. Transparency is kept. Made in your browser, nothing uploaded.',
  about: [
    'A favicon is the small picture a browser shows in the tab, in bookmarks and in the history list. The traditional way to provide one is a file called favicon.ico in the main folder of the website. Browsers ask for that address on their own when a page does not name another icon, which is why this old format is still in use.',
    'Here is exactly what this tool produces. You get one .ico file that contains your image at 16, 24, 32, 48, 64, 128 and 256 pixels. Each size is stored inside the file as a PNG with full transparency. Sizes that would be much larger than your source image are left out so the file is not filled with blurry enlargements: a logo of 100 by 100 pixels, for example, gives the sizes from 16 to 64 only. To get the full set, start with a PNG of at least 256 by 256 pixels.',
    'The best source is square, has a transparent background and is simple. If your PNG is not square, it is not stretched or cropped. It is scaled to fit, placed in the centre, and the leftover space on the short sides stays transparent.',
    'Why several sizes? A browser tab shows the icon at about 16 pixels, or 32 on sharp high density screens. Bookmarks, shortcuts and the Windows taskbar use larger versions. With every size in one file, each of those places can pick a version made for it instead of shrinking a big picture badly.',
    'Design matters more than the conversion. At 16 pixels there is room for one shape and two or three colours. A full company name will turn into a grey smudge. Use the symbol from your logo or a single letter, and check the smallest size in the result before you publish it.',
    'To install the icon, name the file favicon.ico and upload it to the main folder of your site, or point to it with a link tag of type icon in the head of your pages. Browsers keep favicons in their cache for a long time, so after replacing the file you may need a hard refresh or a private window to see the new one. Icons for phone home screens are a separate matter: those use PNG files, not ICO.',
  ],
  when: 'Use it when you are setting up a website and need a favicon.ico, or when you want a Windows shortcut, folder or program to show your own logo. Start from the largest, cleanest square PNG you have.',
  limits: 'The tool does not redraw your logo for small sizes. It only scales it down, so fine detail will blur at 16 pixels. Sources smaller than 256 pixels produce fewer sizes. It makes ICO files only and does not create the separate PNG icons that phones use for home screen shortcuts.',
  how: [
    'Prepare a square PNG of your logo, ideally 256 by 256 pixels or larger, with a transparent background.',
    'Choose the file and press Convert to ICO.',
    'Download the .ico file and rename it to favicon.ico if it is for a website.',
    'Upload it to the main folder of your site, next to your home page.',
    'Open the site in a private window to check the tab icon, since browsers cache the old one.',
  ],
  faq: [
    ['Which sizes are inside the ICO file?', '16, 24, 32, 48, 64, 128 and 256 pixels, as long as your PNG is at least 256 pixels on its longer side. Smaller sources give fewer sizes, because enlarging would only make blurry copies.'],
    ['How do I add the favicon to my website?', 'Name the file favicon.ico and put it in the main folder of the site. Most browsers find it there on their own. You can also point to it with a link tag of type icon in the head of the page.'],
    ['I replaced favicon.ico but the old icon still shows. Why?', 'Browsers cache favicons for a long time. Try a hard refresh, a private window or another browser. Other visitors will see the new icon once their cache expires.'],
    ['What happens if my PNG is not square?', 'It is scaled to fit and centred, and the empty space on the short sides stays transparent. Nothing is cropped or stretched, but the icon will look smaller than a square one.'],
    ['Can I use the file as a Windows shortcut icon?', 'Yes. Right click the shortcut, open Properties, choose Change Icon, then browse to the .ico file.'],
  ],
  links: [
    ['jpg-to-ico', 'builds the icon when your logo only exists as a JPG'],
    ['ico-to-png', 'lets you check what is inside an existing favicon'],
  ],
  guide: ['how-to-create-favicon-ico-from-png', 'Making and installing a favicon step by step'],
},

'jpg-to-ico': {
  title: 'JPG to ICO Converter: Turn a Photo into an Icon',
  desc: 'Make a Windows icon or a favicon from a JPG photo or logo. Square pictures work best. Converted on your device, no upload.',
  about: [
    'People turn JPG files into icons for all sorts of reasons: a family photo for a desktop shortcut, a project folder that should be easy to spot, or a favicon for a site whose logo only exists as a JPG. This tool builds the .ico file for you.',
    'Icons are shown as small squares, and that decides which pictures work. A wide landscape or a group photo turns into an unreadable speck at 16 pixels. A close crop of one face, a single object or a bold logo stays recognisable. The simpler the picture, the better the icon.',
    'What happens when the picture is not square? The tool does not crop it and does not stretch it. It scales the whole picture down until it fits inside the square, puts it in the centre and leaves the rest of the square empty and transparent. A wide photo therefore becomes a narrow strip with empty bands above and below it, and looks smaller than the icons around it. For an icon that fills its space, crop the photo to a square in any photo editor before converting.',
    'Keep in mind what a JPG cannot do. It has no transparency, so the icon will be the full rectangle of your picture, background included. A logo on a white background becomes a white tile, which looks fine on a light desktop and out of place on a dark taskbar. If you need an icon with a cut out shape, you need a PNG with a transparent background and the PNG to ICO converter.',
    'Logos saved as JPG often have faint specks around their edges, left by JPG compression. They are easy to miss in the original and become more visible in the larger icon sizes. Use the highest quality copy of the picture that you can find.',
    'The .ico file contains your picture at sizes from 16 up to 256 pixels. A source smaller than 256 pixels gives fewer sizes, because enlarging would only blur it. To use the icon in Windows, right click a shortcut, open Properties, choose Change Icon and browse to the file.',
  ],
  when: 'Use it when the only version of your picture or logo is a JPG and you need a Windows icon or a simple favicon from it. If you have the same logo as a PNG with a transparent background, convert that file instead for a cleaner result.',
  limits: 'The icon cannot have a transparent or rounded shape, because a JPG has no transparency to begin with. Pictures that are not square leave empty space in the icon. Small or heavily compressed JPG files give soft icons.',
  how: [
    'Crop your picture to a square first, if it is not square already.',
    'Choose the JPG file and press Convert to ICO.',
    'Look at the preview to see how the picture sits inside the square.',
    'Download the .ico file.',
    'For a shortcut in Windows: right click it, open Properties, choose Change Icon and select the file.',
  ],
  faq: [
    ['What size should my JPG be?', 'Square and at least 256 by 256 pixels. That gives the full set of icon sizes and the sharpest result.'],
    ['My picture is wide and not square. What will the icon look like?', 'The whole picture is fitted into the square and centred, with empty space above and below. Crop it to a square first if you want it to fill the icon.'],
    ['Can the icon have a transparent background or a round shape?', 'Not when it starts from a JPG, because the JPG has a solid background. Use a PNG with a transparent background and the PNG to ICO converter for that.'],
    ['How do I set the icon on a Windows shortcut?', 'Right click the shortcut, choose Properties, then Change Icon, then Browse, and pick the .ico file.'],
    ['Why is my photo hard to recognise as a small icon?', 'At 16 or 32 pixels there is room for very little detail. Pick a close up of one subject, or a simple symbol with strong contrast.'],
  ],
  links: [
    ['png-to-ico', 'gives a cleaner icon when you have a PNG with transparency'],
    ['jpg-to-png', 'is the first step if you want to cut out the background in an editor'],
    ['ico-to-png', 'lets you view the icon you made as a normal picture'],
  ],
  guide: ['how-to-convert-jpg-to-ico-favicon', 'Choosing and preparing a picture that works as an icon'],
},

'avif-to-png': {
  title: 'AVIF to PNG Converter: Open AVIF Files Anywhere',
  desc: 'Convert .avif images to PNG so they open in editors and documents. Needs a browser that can display AVIF. Nothing is uploaded.',
  about: [
    'AVIF is a fairly new image format. It is based on the AV1 video codec and was developed by the Alliance for Open Media, a group of large technology companies. Its main strength is that it often produces small files at good quality, and it supports transparency. More and more websites deliver their pictures as AVIF for that reason.',
    'The trouble starts when you save one of those pictures. AVIF is newer than WebP, and outside web browsers the support is patchy. Many image editors, office programs and older picture viewers on Windows, macOS and Android either cannot open .avif files or need an extra add on first.',
    'There is one requirement you should know before using this page. The tool relies on your browser to read the AVIF file. Recent versions of Chrome, Edge, Firefox and Safari can do that. If your browser is too old, the tool cannot open the file and tells you so with a message. Updating the browser, or trying a different one, solves it.',
    'Converting to PNG is the right step when you want to edit the picture. PNG is lossless, so you can open it, change it and save it as often as you like without wearing it down, and a transparent background stays transparent. What PNG cannot do is restore detail that the AVIF file had already discarded.',
    'Be ready for a much bigger file. AVIF is very efficient and PNG is not, so an AVIF photo of a few hundred kilobytes can turn into a PNG of several megabytes. If you only want to send the picture to someone, convert the PNG onward with the PNG to JPG tool to get a small file that opens everywhere.',
    'The width and height of the picture are not changed. Several files can be converted in one run and downloaded together as a ZIP file.',
    'Two special cases. AVIF files can contain animations, and this tool saves only a single still picture from them. AVIF can also carry high dynamic range and very wide colour. The PNG made here is a standard picture with eight bits per colour channel, so such images may look a little flatter after conversion.',
  ],
  when: 'Use it when a downloaded .avif picture will not open in your editor, cannot be inserted into a document, or is refused by a website, and you want a copy you can work with.',
  limits: 'Your browser must be able to display AVIF. The PNG is usually many times larger than the AVIF. Animated AVIF files become one still image, and high dynamic range pictures are saved as standard images. HEIC photos from iPhones are a different format and will usually not open here.',
  how: [
    'Choose your .avif files. If they do not appear in the file picker on your phone, look in the full file list.',
    'Press Convert to PNG.',
    'If a file cannot be opened, read the message. It usually means the browser is too old for AVIF.',
    'Download the PNG files one by one or as a ZIP file.',
  ],
  faq: [
    ['Why can I not open AVIF files on my computer?', 'AVIF is a newer format and many programs have not added support for it. Browsers were the first to support it, which is why this tool works inside one.'],
    ['The tool says my file could not be opened. What should I do?', 'Update your browser or try another one, such as a current Chrome, Edge, Firefox or Safari. If it still fails there, the file itself may be damaged.'],
    ['Why is the PNG many times larger than the AVIF?', 'AVIF keeps files small by discarding detail very cleverly. PNG stores every pixel exactly, and that takes far more space.'],
    ['How do I get a JPG instead of a PNG?', 'Convert the file to PNG here, then run that PNG through the PNG to JPG tool. That gives a small file suitable for sharing.'],
    ['Is AVIF the same as HEIC?', 'No. HEIC is the format iPhones use for photos, and it is built on a different video codec. This tool is made for .avif files.'],
  ],
  links: [
    ['png-to-jpg', 'turns the large PNG into a small JPG for sharing'],
    ['png-to-avif', 'creates AVIF files when you need them for a website'],
    ['webp-to-png', 'solves the same problem for the older WebP format'],
  ],
  guide: ['how-to-convert-avif-to-png', 'What to do with an AVIF file that will not open'],
},

'png-to-avif': {
  title: 'PNG to AVIF Converter: Small Images for the Web',
  desc: 'Convert PNG images to AVIF for lighter web pages. The AVIF encoder runs on your device and takes a few seconds per image.',
  about: [
    'AVIF is aimed at one thing: sending good looking pictures over the internet in as few bytes as possible. If you run a website and want large images to load faster, converting PNG files to AVIF is one of the options to test, next to WebP.',
    'It is worth explaining how this page works, because it differs from our other converters. Browsers can display AVIF, but they generally cannot save pictures in that format on their own. So the first time you convert, this tool downloads an open source AVIF encoder that runs on your device, and then does the encoding there. That download needs an internet connection. Your image is not uploaded. Only the encoder program is fetched.',
    'Encoding AVIF is heavy work. Expect a few seconds for a normal image and noticeably longer for a large one, and the first image takes longest because the encoder has to load. On a phone with little free memory, a very large image can fail, and you will get a message asking you to try a smaller one. We have checked the converter in desktop Chrome. If the encoder cannot be loaded in your browser, you see a clear message and no broken file is produced.',
    'The quality slider starts at 60. AVIF quality numbers do not match JPG numbers, and 60 already looks good for most pictures. Raise it for screenshots with small text, and lower it for big background photos where fine detail matters less. Transparent backgrounds are kept.',
    'Think about who has to display the result. Current versions of the major browsers show AVIF, but older versions do not, and outside browsers many programs still cannot open it. On a website, the usual approach is to offer the AVIF together with a PNG or WebP fallback, so every visitor gets a picture. Keep your PNG originals for that.',
    'There are cases where converting is not worth it. Files you will email or put in a document should stay PNG or JPG. Tiny icons save almost nothing. And if your site builder does not accept AVIF uploads, WebP is the practical choice.',
  ],
  when: 'Use it when you manage a website, want the smallest image files you can get, and can serve a fallback for older browsers. For everyday sharing, printing and documents, AVIF is the wrong format.',
  limits: 'Conversion is slow compared with the other formats and needs an internet connection the first time, to download the encoder. Very large images may fail on devices with little memory. Many programs outside web browsers cannot open AVIF files, so always keep the PNG.',
  how: [
    'Choose one or a few PNG files. Start with one to see how long your device needs.',
    'Leave the quality at 60 for a first try.',
    'Press Convert to AVIF and wait. The first image includes the download of the encoder.',
    'Compare the sizes in the list, and open the result in a browser tab to check how it looks.',
    'Download the AVIF files and keep the PNG originals as a fallback.',
  ],
  faq: [
    ['Why does making an AVIF take longer than other formats?', 'The AVIF method examines the picture far more thoroughly to find savings, and that takes computing time. Here it also runs on your own device and not on a server.'],
    ['Can every browser display AVIF images?', 'Current versions of Chrome, Edge, Firefox and Safari can. Older versions cannot, so a website should keep a PNG or WebP version as a fallback.'],
    ['Is the transparent background kept in the AVIF file?', 'Yes. AVIF supports transparency and the converter keeps it.'],
    ['AVIF or WebP: which should I use on my site?', 'AVIF files are often smaller. WebP is quicker to create and is accepted by more software. Many sites offer AVIF first and fall back to WebP or PNG.'],
    ['It says the converter could not be loaded. Why?', 'The AVIF encoder is downloaded the first time you convert. Check your internet connection, and whether an ad blocker or a company firewall is blocking the download, then try again.'],
  ],
  links: [
    ['png-to-webp', 'is faster and its files open in more programs'],
    ['avif-to-png', 'converts an AVIF back when someone cannot open it'],
  ],
  guide: ['how-to-convert-png-to-avif', 'Using AVIF on a website without breaking older browsers'],
},
};
