// Naya blog post add karne ke liye is array mein ek object copy karo.
// content blocks: {h:'heading'} {p:'paragraph'} {ul:['a','b']} {ol:['a','b']}
export const posts = [
{
  slug: 'how-to-convert-pdf-to-word-for-free',
  title: 'How to Convert PDF to Word for Free (No Software Needed)',
  desc: 'Learn three simple ways to turn a PDF into an editable Word document without paying for Adobe Acrobat.',
  date: '2026-10-01', tool: 'pdf-to-word',
  content: [
    { p: 'You receive a PDF that needs a few changes, but a PDF is built to be read, not edited. The usual fix is to convert it to a Word document. Many people assume this requires Adobe Acrobat, which costs money every month. It does not. Here is how to do it for free.' },
    { h: 'Why PDFs are hard to edit' },
    { p: 'A PDF stores text as positioned pieces on a page, like a printed sheet. Word stores text as flowing paragraphs. A converter has to read those positions and rebuild paragraphs from them, which is why results are never 100 percent perfect.' },
    { h: 'Method 1: Use a free online converter in your browser' },
    { p: 'The fastest option is a browser-based tool. Open our PDF to Word converter, choose your file, and press Convert. Because the conversion runs inside your browser, your file is not uploaded to a server, which matters for CVs, contracts and university documents.' },
    { h: 'Method 2: Open the PDF directly in Microsoft Word' },
    { p: 'Recent versions of Word can open a PDF directly. Go to File, then Open, choose the PDF and Word will offer to convert it. This works well for simple text documents but can struggle with complex layouts.' },
    { h: 'Method 3: Use Google Docs' },
    { p: 'Upload the PDF to Google Drive, right click it, and choose Open with Google Docs. Google converts the text into an editable document that you can download as a Word file.' },
    { h: 'What to expect after converting' },
    { ul: ['Plain text and headings usually convert well.', 'Tables and multi-column layouts may need manual fixing.', 'Images may move or be dropped.', 'Fonts can change if the original font is not installed.'] },
    { h: 'A note about scanned PDFs' },
    { p: 'If your PDF is a scan or a photo of a page, there is no real text inside it, only a picture. Converters that do not include OCR (optical character recognition) cannot read it. In that case you need an OCR tool, or you can retype the content.' },
    { h: 'Tips for the best result' },
    { ol: ['Start from the original digital PDF, not a scan or screenshot.', 'Keep the PDF simple. Fewer columns and images convert better.', 'Check the converted file for spacing and fix headings before sending.', 'Keep a copy of the original PDF.'] },
    { p: 'For most everyday documents, a browser-based converter is enough and takes under a minute.' },
  ],
},
{
  slug: 'reduce-image-size-without-losing-quality',
  title: 'How to Reduce Image Size Without Losing Quality',
  desc: 'Large photos are hard to email and upload. Here is how to shrink JPG and PNG files while keeping them sharp.',
  date: '2026-10-01', tool: 'image-compressor',
  content: [
    { p: 'Modern phones take photos that are 3 to 10 MB each. That is too big for many job portals, university forms and email attachments, and it slows down websites. The good news is that you can usually cut the size by 60 to 80 percent with very little visible change.' },
    { h: 'Why image files are so large' },
    { p: 'A photo contains millions of pixels and a lot of fine colour detail that the human eye barely notices. Compression removes some of that hidden detail, which is why the file shrinks while the picture still looks the same at normal viewing size.' },
    { h: 'Lossy versus lossless compression' },
    { ul: ['Lossy (JPG): discards some data. Much smaller files, tiny quality loss at moderate settings.', 'Lossless (PNG): keeps all data. Larger files, ideal for logos and screenshots with sharp edges.'] },
    { h: 'How to compress an image step by step' },
    { ol: ['Open the Image Compressor tool.', 'Choose your photo.', 'Set the quality slider to around 70 percent.', 'Press Compress and compare the before and after size.', 'Download the result.'] },
    { h: 'Which quality setting should you use?' },
    { p: 'For photos, 60 to 80 percent is the sweet spot. Below 50 percent you may notice blocky patches around edges. For documents and screenshots that contain text, use a higher setting so the letters stay crisp.' },
    { h: 'Other ways to make images smaller' },
    { ul: ['Resize the dimensions. A 4000 pixel wide photo is unnecessary for a web page that shows it at 800 pixels.', 'Choose the right format. Use JPG for photos and PNG for graphics.', 'Remove metadata such as GPS location, which also protects your privacy.'] },
    { h: 'Common size limits' },
    { p: 'Many forms ask for files under 100 KB, 200 KB or 500 KB. Compress once, check the size, and lower the quality a little more if you are still over the limit.' },
    { p: 'A quick compression takes seconds and saves storage, bandwidth and upload time.' },
  ],
},
{
  slug: 'how-to-merge-pdf-files-without-software',
  title: 'How to Merge PDF Files Without Installing Software',
  desc: 'Combine several PDFs into one file in a few clicks, including tips for job applications and university submissions.',
  date: '2026-10-01', tool: 'merge-pdf',
  content: [
    { p: 'Job portals, universities and offices often ask for a single PDF, while your documents are spread across several files. Merging them takes a minute and needs no installation.' },
    { h: 'When merging PDFs is useful' },
    { ul: ['Combining a CV, cover letter and certificates into one application file.', 'Joining scanned pages into a single document.', 'Putting invoices or receipts for one month in one file.', 'Bundling assignment chapters into one submission.'] },
    { h: 'How to merge PDFs online' },
    { ol: ['Open the Merge PDF tool.', 'Select two or more PDF files. They are joined in the order you select them.', 'Press Merge PDFs.', 'Download merged.pdf.'] },
    { p: 'The merge runs in your browser, so your documents stay on your device.' },
    { h: 'Get the order right' },
    { p: 'Select the files in the exact order you want them to appear. If you get it wrong, simply run the merge again with the correct order. Name your files 1, 2, 3 before selecting to keep track.' },
    { h: 'Reduce the size of the final file' },
    { p: 'Merged files can become large, especially with scanned pages. Many portals have a limit such as 2 MB or 5 MB. Compress the images before turning them into PDFs, or scan at a lower resolution such as 150 DPI.' },
    { h: 'If a file will not merge' },
    { ul: ['The PDF may be password protected. Remove the password first.', 'The file may be damaged. Try re-saving or re-exporting it.', 'Very large files can be slow on older phones. Try a computer.'] },
    { h: 'Tips for job applications' },
    { p: 'Put your CV first, then the cover letter, then certificates in order of importance. Keep the total under the size limit and use a clear file name such as YourName-Application.pdf.' },
  ],
},
{
  slug: 'how-to-create-a-strong-password',
  title: 'How to Create a Strong Password You Can Actually Use',
  desc: 'What makes a password strong, how long it should be, and how to keep track of many passwords safely.',
  date: '2026-10-01', tool: 'password-generator',
  content: [
    { p: 'Most account hacks happen because of weak or reused passwords, not clever attacks. A few simple habits protect you far better than complicated tricks.' },
    { h: 'What makes a password strong' },
    { ul: ['Length: at least 12 characters, ideally 16 or more.', 'Randomness: not a name, birth year or keyboard pattern.', 'Uniqueness: a different password for every important account.'] },
    { p: 'Length matters more than special characters. A long random password is much harder to crack than a short one full of symbols.' },
    { h: 'Passwords to avoid' },
    { ul: ['123456, password, qwerty and similar common choices.', 'Your name, phone number or date of birth.', 'The same password reused on several sites.', 'Small changes like Password1 and Password2.'] },
    { h: 'Use a generator instead of inventing one' },
    { p: 'Humans are bad at being random. Use our Password Generator to create a password of 16 or more characters. It uses your browser secure random source and never stores or sends the result.' },
    { h: 'How to remember many passwords' },
    { p: 'Nobody can memorise dozens of random passwords. Use a reputable password manager and protect it with one strong master password. Many browsers also include a built-in manager.' },
    { h: 'Turn on two-factor authentication' },
    { p: 'Two-factor authentication adds a second step, such as a code from an authenticator app. Even if someone learns your password, they cannot log in without it. Enable it first on your email, banking and social media accounts.' },
    { h: 'What to do after a data breach' },
    { ol: ['Change the password on that site immediately.', 'Change it anywhere else you reused it.', 'Check for unfamiliar logins.', 'Enable two-factor authentication.'] },
  ],
},
];
export const getPost = (s) => posts.find((p) => p.slug === s);
