export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://yourdomain.com';
export const tools = [
{ slug:'pdf-to-word', name:'PDF to Word', badge:'PDF', cls:'b-pdf', cat:'Convert',
  title:'PDF to Word Converter - Free, No Signup', desc:'Convert PDF to an editable Word file for free. No signup, no watermark. Your file never leaves your browser.',
  sub:'Turn the text of a PDF into an editable Word document.',
  about:'This free PDF to Word converter pulls the text out of your PDF and saves it as a Word file you can edit. It runs entirely in your browser, so your document is never uploaded to any server. That makes it a safe choice for CVs, contracts and university assignments. It works best on text-based PDFs. Scanned or image-only PDFs are read with OCR (English) right in your browser, which is slower and can make small mistakes.',
  how:['Click the box and choose your PDF.','Press Convert to Word.','Download the .doc file and open it in Microsoft Word or Google Docs.'],
  faq:[['Is it really free?','Yes. There is no limit, no signup and no watermark.'],['Is my file uploaded?','No. The conversion happens inside your browser.'],['Will the layout stay the same?','Text is kept, but complex layouts, images and tables may change.']] },
{ slug:'pdf-to-excel', name:'PDF to Excel', badge:'XLS', cls:'b-xls', cat:'Convert',
  title:'PDF to Excel Converter - Free Online', desc:'Convert PDF tables to an Excel spreadsheet (.xlsx) for free. Works in your browser with no upload.',
  sub:'Move PDF tables and lists into an Excel spreadsheet.',
  about:'This tool reads the text in your PDF, groups it into rows by position and splits each row into columns wherever there is a wide gap. Every PDF page becomes its own sheet in the Excel file. It works well for statements, price lists and simple tables. Nothing is uploaded, because all processing happens on your device.',
  how:['Choose a PDF that contains a table.','Press Convert to Excel.','Download the .xlsx file and fix any columns in Excel if needed.'],
  faq:[['Which PDFs work best?','Text-based PDFs with simple tables. Scanned PDFs also work through OCR (English), but the result may need small fixes.'],['Is there a page limit?','No fixed limit, but very large files depend on your device.'],['Is my data safe?','Yes. The file stays in your browser.']] },
{ slug:'word-to-pdf', name:'Word to PDF', badge:'DOC', cls:'b-doc', cat:'Convert',
  title:'Word to PDF Converter - Free DOCX to PDF', desc:'Convert Word (.docx) files to PDF online for free. No signup, no watermark, no upload.',
  sub:'Convert a .docx document into a PDF.',
  about:'Convert a Word document to PDF in a few seconds. The tool reads your .docx file in the browser and creates an A4 PDF with your headings, paragraphs, lists and tables. Nothing is sent to a server. Very fancy formatting such as text boxes or special fonts can look different in the result.',
  how:['Choose your .docx file.','Press Convert to PDF.','Download the finished PDF.'],
  faq:[['Does it support .doc files?','Only .docx. Save older files as .docx in Word first.'],['Is there a watermark?','No.'],['Are my files stored?','No. Everything runs locally in your browser.']] },
{ slug:'merge-pdf', name:'Merge PDF', badge:'PDF', cls:'b-pdf', cat:'PDF',
  title:'Merge PDF Files Online - Free', desc:'Combine multiple PDF files into one document for free. No signup and no upload.',
  sub:'Combine several PDF files into a single document.',
  about:'Merge PDF joins two or more PDF files into one, in the order you select them. It is useful for combining scanned pages, invoices, application documents and reports. The merge happens in your browser, so the files stay private.',
  how:['Select two or more PDF files.','Press Merge PDFs.','Download merged.pdf.'],
  faq:[['How many files can I merge?','As many as your device can handle.'],['Can I change the order?','Files are merged in the order you select them.'],['Is it private?','Yes. Nothing is uploaded.']] },
{ slug:'image-compressor', name:'Image Compressor', badge:'IMG', cls:'b-img', cat:'Image',
  title:'Image Compressor - Reduce JPG and PNG Size Free', desc:'Compress images online for free. Reduce JPG and PNG file size while keeping good quality. No upload.',
  sub:'Make image files smaller without visible quality loss.',
  about:'Large photos slow down websites and are hard to email or upload to forms with size limits. This compressor re-encodes your image as an optimised JPG and shows the size before and after. A quality of about 70 percent usually gives a much smaller file with little visible difference.',
  how:['Choose an image.','Set the quality slider (70 is a good start).','Press Compress and download the result.'],
  faq:[['What format is the output?','JPG.'],['Which quality should I use?','Between 60 and 80 for most photos.'],['Are images uploaded?','No. Compression happens in your browser.']] },
{ slug:'qr-code-generator', name:'QR Code Generator', badge:'QR', cls:'b-qr', cat:'Generators',
  title:'QR Code Generator - Free, No Signup', desc:'Create a QR code for any link or text and download it as a PNG. Free and unlimited.',
  sub:'Create a QR code from a link or any text.',
  about:'Type a website link, phone number or any text and get a scannable QR code instantly. Download it as a PNG to print on cards, menus and posters. QR codes made here never expire and are not tracked.',
  how:['Enter your link or text.','Press Generate QR.','Download the PNG image.'],
  faq:[['Do the codes expire?','No. The link or text is stored inside the code itself.'],['Is it free for commercial use?','Yes.'],['Can I scan it with any phone?','Yes, any modern camera app can.']] },
{ slug:'word-counter', name:'Word Counter', badge:'TXT', cls:'b-txt', cat:'Text',
  title:'Word Counter - Count Words and Characters Online', desc:'Count words, characters, sentences and reading time instantly. Works with English and Urdu text.',
  sub:'Count words, characters and sentences as you type.',
  about:'Paste or type your text to see the number of words, characters, sentences and the estimated reading time. It is handy for essays, social media posts, SEO articles and any text with a length limit. It also works with Urdu text.',
  how:['Paste or type your text.','Read the live counts below.','Edit until you reach your target length.'],
  faq:[['How is reading time calculated?','About 200 words per minute.'],['Does it support Urdu?','Yes.'],['Is my text saved?','No.']] },
{ slug:'case-converter', name:'Case Converter', badge:'Aa', cls:'b-txt', cat:'Text',
  title:'Case Converter - Uppercase, Lowercase, Title Case', desc:'Convert text to UPPERCASE, lowercase, Title Case or Sentence case in one click.',
  sub:'Change the letter case of any text in one click.',
  about:'Fix text that was typed with caps lock on, format headings in Title Case, or turn a paragraph into proper sentence case. Paste your text, pick a style and copy the result.',
  how:['Paste your text.','Choose a case style.','Copy the result.'],
  faq:[['What styles are available?','Uppercase, lowercase, Title Case and Sentence case.'],['Is there a length limit?','No.'],['Is my text stored?','No.']] },
{ slug:'password-generator', name:'Password Generator', badge:'***', cls:'b-qr', cat:'Generators',
  title:'Strong Password Generator - Free and Secure', desc:'Generate strong random passwords instantly. Created in your browser and never stored or sent anywhere.',
  sub:'Create strong random passwords that are never sent anywhere.',
  about:'Weak and reused passwords are the most common way accounts get hacked. This generator uses your browser secure random number source to create passwords of 8 to 40 characters. Passwords are created on your device and are never stored or transmitted.',
  how:['Pick a length. 16 or more is recommended.','Choose numbers and symbols.','Press Generate and copy the password.'],
  faq:[['Is it secure?','It uses the browser cryptographic random generator.'],['Do you store passwords?','No.'],['How long should a password be?','At least 12 characters, ideally 16 or more.']] },
];
export const getTool = (s) => tools.find((t) => t.slug === s);
