export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://docbrio.me';
export const tools = [
{ slug:'pdf-to-word', name:'PDF to Word', badge:'PDF', cls:'b-pdf', cat:'Convert',
  title:'PDF to Word Converter - Free, No Signup', desc:'Convert PDF to an editable Word file for free. No signup, no watermark. Your file never leaves your browser.',
  sub:'Turn the text of a PDF into an editable Word document.',
  about:'This free PDF to Word converter pulls the text out of your PDF and saves it as a Word file you can edit. It runs entirely in your browser, so your document is never uploaded to any server. That makes it a safe choice for CVs, contracts and university assignments. It works best on text-based PDFs. Scanned or image-only PDFs are read with OCR (English) right in your browser, which is slower and can make small mistakes.',
  how:['Click the box and choose your PDF.','Press Convert to Word.','Download the .docx file and open it in Microsoft Word or Google Docs.'],
  faq:[['Is it really free?','Yes. There is no limit, no signup and no watermark.'],['Is my file uploaded?','No. The conversion happens inside your browser.'],['Will the layout stay the same?','Text is kept, but complex layouts, images and tables may change.']] },
{ slug:'pdf-to-excel', name:'PDF to Excel', badge:'XLS', cls:'b-xls', cat:'Convert',
  title:'PDF to Excel Converter - Free Online', desc:'Convert PDF tables to an Excel spreadsheet (.xlsx) for free. Works in your browser with no upload.',
  sub:'Move PDF tables and lists into an Excel spreadsheet.',
  about:'This tool reads the text in your PDF, groups it into rows by position and splits each row into columns wherever there is a wide gap. Every PDF page becomes its own sheet in the Excel file. It works well for statements, price lists and simple tables. Nothing is uploaded, because all processing happens on your device.',
  how:['Choose a PDF that contains a table.','Press Convert to Excel.','Download the .xlsx file and fix any columns in Excel if needed.'],
  faq:[['Which PDFs work best?','Text-based PDFs with simple tables. Scanned PDFs also work through OCR (English), but the result may need small fixes.'],['Is there a page limit?','No fixed limit, but very large files depend on your device.'],['Is my data safe?','Yes. The file stays in your browser.']] },
{ slug:'word-to-pdf', name:'Word to PDF', badge:'DOC', cls:'b-doc', cat:'Convert',
  title:'Word to PDF Converter - Free DOCX to PDF', desc:'Convert Word (.docx) files to PDF online for free. No signup, no watermark, no upload.',
  sub:'Convert a .docx document into a PDF.',
  about:'Convert a Word document to PDF in a few seconds. The tool reads your .docx file in the browser and creates an A4 PDF with your headings, paragraphs, lists and tables. Nothing is sent to a server. Very fancy formatting such as text boxes or special fonts can look different in the result.',
  how:['Choose your .docx file.','Press Convert to PDF.','Download the finished PDF.'],
  faq:[['Does it support .doc files?','Only .docx. Save older files as .docx in Word first.'],['Is there a watermark?','No.'],['Are my files stored?','No. Everything runs locally in your browser.']] },
{ slug:'merge-pdf', name:'Merge PDF', badge:'PDF', cls:'b-pdf', cat:'PDF',
  title:'Merge PDF Files Online - Free', desc:'Combine multiple PDF files into one document for free. No signup and no upload.',
  sub:'Combine several PDF files into a single document.',
  about:'Merge PDF joins two or more PDF files into one, in the order you select them. It is useful for combining scanned pages, invoices, application documents and reports. The merge happens in your browser, so the files stay private.',
  how:['Select two or more PDF files.','Press Merge PDFs.','Download merged.pdf.'],
  faq:[['How many files can I merge?','As many as your device can handle.'],['Can I change the order?','Files are merged in the order you select them.'],['Is it private?','Yes. Nothing is uploaded.']] },
{ slug:'image-compressor', name:'Image Compressor', badge:'IMG', cls:'b-img', cat:'Image',
  title:'Image Compressor - Reduce JPG and PNG Size Free', desc:'Compress images online for free. Reduce JPG and PNG file size while keeping good quality. No upload.',
  sub:'Make image files smaller without visible quality loss.',
  about:'Large photos slow down websites and are hard to email or upload to forms with size limits. This compressor re-encodes your image as an optimised JPG and shows the size before and after. A quality of about 70 percent usually gives a much smaller file with little visible difference.',
  how:['Choose an image.','Set the quality slider (70 is a good start).','Press Compress and download the result.'],
  faq:[['What format is the output?','JPG.'],['Which quality should I use?','Between 60 and 80 for most photos.'],['Are images uploaded?','No. Compression happens in your browser.']] },
{ slug:'qr-code-generator', name:'QR Code Generator', badge:'QR', cls:'b-qr', cat:'Generators',
  title:'QR Code Generator - Free, No Signup', desc:'Create a QR code for any link or text and download it as a PNG. Free and unlimited.',
  sub:'Create a QR code from a link or any text.',
  about:'Type a website link, phone number or any text and get a scannable QR code instantly. Download it as a PNG to print on cards, menus and posters. QR codes made here never expire and are not tracked.',
  how:['Enter your link or text.','Press Generate QR.','Download the PNG image.'],
  faq:[['Do the codes expire?','No. The link or text is stored inside the code itself.'],['Is it free for commercial use?','Yes.'],['Can I scan it with any phone?','Yes, any modern camera app can.']] },
{ slug:'word-counter', name:'Word Counter', badge:'TXT', cls:'b-txt', cat:'Text',
  title:'Word Counter - Count Words and Characters Online', desc:'Count words, characters, sentences and reading time instantly. Works with English and Urdu text.',
  sub:'Count words, characters and sentences as you type.',
  about:'Paste or type your text to see the number of words, characters, sentences and the estimated reading time. It is handy for essays, social media posts, SEO articles and any text with a length limit. It also works with Urdu text.',
  how:['Paste or type your text.','Read the live counts below.','Edit until you reach your target length.'],
  faq:[['How is reading time calculated?','About 200 words per minute.'],['Does it support Urdu?','Yes.'],['Is my text saved?','No.']] },
{ slug:'case-converter', name:'Case Converter', badge:'Aa', cls:'b-txt', cat:'Text',
  title:'Case Converter - Uppercase, Lowercase, Title Case', desc:'Convert text to UPPERCASE, lowercase, Title Case or Sentence case in one click.',
  sub:'Change the letter case of any text in one click.',
  about:'Fix text that was typed with caps lock on, format headings in Title Case, or turn a paragraph into proper sentence case. Paste your text, pick a style and copy the result.',
  how:['Paste your text.','Choose a case style.','Copy the result.'],
  faq:[['What styles are available?','Uppercase, lowercase, Title Case and Sentence case.'],['Is there a length limit?','No.'],['Is my text stored?','No.']] },
{ slug:'password-generator', name:'Password Generator', badge:'***', cls:'b-qr', cat:'Generators',
  title:'Strong Password Generator - Free and Secure', desc:'Generate strong random passwords instantly. Created in your browser and never stored or sent anywhere.',
  sub:'Create strong random passwords that are never sent anywhere.',
  about:'Weak and reused passwords are the most common way accounts get hacked. This generator uses your browser secure random number source to create passwords of 8 to 40 characters. Passwords are created on your device and are never stored or transmitted.',
  how:['Pick a length. 16 or more is recommended.','Choose numbers and symbols.','Press Generate and copy the password.'],
  faq:[['Is it secure?','It uses the browser cryptographic random generator.'],['Do you store passwords?','No.'],['How long should a password be?','At least 12 characters, ideally 16 or more.']] },
{ slug:'powerpoint-to-pdf', name:'PowerPoint to PDF', badge:'PPT', cls:'b-ppt', cat:'Convert',
  title:'PowerPoint to PDF Converter - Free PPTX to PDF', desc:'Convert PowerPoint (.pptx) slides to a PDF online for free. No signup, no watermark, and your file is never uploaded.',
  sub:'Turn a .pptx presentation into a PDF, one slide per page.',
  about:'This tool turns a PowerPoint presentation into a PDF that anyone can open, print or share, even without PowerPoint installed. It reads your .pptx file inside your browser and draws every slide on its own PDF page with its text, pictures, shapes and tables. Nothing is uploaded to a server. Charts, SmartArt, animations and special fonts are not supported, so slides that use them can look different from the original.',
  how:['Choose your .pptx file.','Press Convert to PDF.','Download the PDF and check the pages.'],
  faq:[['Does it support old .ppt files?','No, only .pptx. Open the file in PowerPoint or Google Slides and save it as .pptx first.'],['Will my slides look exactly the same?','Text, pictures, shapes and tables are kept. Charts, SmartArt, animations and special fonts may look different or be missing.'],['Is my presentation uploaded?','No. The conversion happens inside your browser.']] },
{ slug:'pdf-to-powerpoint', name:'PDF to PowerPoint', badge:'PPT', cls:'b-ppt', cat:'Convert',
  title:'PDF to PowerPoint Converter - Free PDF to PPTX', desc:'Convert a PDF to PowerPoint (.pptx) slides for free. Each page becomes a slide. No signup and no upload.',
  sub:'Turn every PDF page into a PowerPoint slide.',
  about:'This tool makes a PowerPoint presentation from a PDF. Every page of the PDF becomes one slide that looks exactly like the page, and the slide size matches the page size. It is useful when you need to present a report, a scanned handout or a document that was only shared as a PDF. Each page is placed on the slide as a picture, so you can add your own text boxes, shapes and notes on top, but the original text cannot be retyped. Everything runs in your browser and the file is never uploaded.',
  how:['Choose your PDF.','Press Convert to PowerPoint.','Download the .pptx file and open it in PowerPoint, Google Slides or Keynote.'],
  faq:[['Can I edit the text on the slides?','No. Each page is a picture on the slide. You can add new text, shapes and notes on top of it.'],['Which apps can open the result?','PowerPoint, Google Slides, Keynote and LibreOffice Impress.'],['Is there a page limit?','No fixed limit, but very long PDFs depend on the memory of your device.']] },
{ slug:'edit-pdf', name:'Edit PDF', badge:'PDF', cls:'b-pdf', cat:'PDF',
  title:'Edit PDF Online - Free PDF Editor', desc:'Add text, white out mistakes and draw on a PDF for free. No signup, no watermark, and the file stays in your browser.',
  sub:'Add text, cover mistakes with white and draw on any page.',
  about:'This free PDF editor lets you fill in a form, add a note, fix a small mistake or mark up a page without installing anything. Click anywhere on a page to add text, drag a white box over something you want to hide, or draw with your mouse or finger. When you save, the changes are written into the PDF and the rest of the document stays as sharp as before. The file never leaves your browser. Text that is already in the PDF cannot be retyped directly, but you can cover it with white and write the correct text over it.',
  how:['Choose your PDF.','Pick Text, Whiteout or Draw and make your changes on the page.','Press Save PDF and download the edited file.'],
  faq:[['Can I change the existing text?','Not directly. Cover it with the Whiteout tool and type the new text on top.'],['Can I fill in a form?','Yes. Use the Text tool, click on each blank and type.'],['Is my file uploaded?','No. Editing happens inside your browser.']] },
{ slug:'sign-pdf', name:'Sign PDF', badge:'PDF', cls:'b-pdf', cat:'PDF',
  title:'Sign PDF Online - Free, No Signup', desc:'Draw or type your signature and add it to a PDF for free. No signup and no upload. Your document stays on your device.',
  sub:'Draw or type your signature and place it on a PDF.',
  about:'Sign a contract, form or letter without printing and scanning it. Draw your signature with a mouse, a finger or a pen, or type your name in a handwriting style. Then click on the page to place it, drag it into position and resize it. You can also add the date or your printed name as text. Your document and your signature are processed in your browser and are never sent to a server. This adds a picture of your signature to the page. It is not a certificate-based digital signature, so check what the person receiving the document requires.',
  how:['Choose your PDF.','Draw or type your signature and press Use this signature.','Click on the page to place it, then press Save signed PDF.'],
  faq:[['Is this a legal signature?','It adds an image of your signature, which many people and companies accept. It is not a certificate-based digital signature, so ask the receiver if you are unsure.'],['Can I sign on my phone?','Yes. Draw your signature with your finger.'],['Is my signature stored?','No. It stays in your browser and is gone when you close the page.']] },
{ slug:'crop-pdf', name:'Crop PDF', badge:'PDF', cls:'b-pdf', cat:'PDF',
  title:'Crop PDF Online - Free PDF Cropper', desc:'Crop PDF pages to remove margins or keep only one part of a page. Free, no signup, and no upload.',
  sub:'Cut away margins or keep only one part of each page.',
  about:'Crop PDF trims the pages of a document to the area you choose. Use it to remove wide white margins, cut off headers and footers, or keep only one part of a page such as a table or a ticket. Drag a box over the area you want to keep and choose whether to crop only the current page or all pages the same way. The text inside the cropped area stays sharp and selectable, because the page is not turned into a picture. The file is processed in your browser and is never uploaded.',
  how:['Choose your PDF.','Drag on the page to mark the area you want to keep.','Press Crop PDF and download the result.'],
  faq:[['Can I crop all pages at once?','Yes. Keep "Crop all pages the same way" ticked.'],['Does cropping reduce quality?','No. Text and images stay exactly as sharp as before.'],['Is the hidden part deleted?','It is hidden and the page becomes smaller, but the hidden content is still inside the file. Do not use cropping to remove confidential information.']] },
];
export const getTool = (s) => tools.find((t) => t.slug === s);
